/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 BuildingHoardingText.glb --transform
*/

import { useAnimations, useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'

export function BuildingHoardingText(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/BuildingHoardingText-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group scale={0.1} ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Text001" geometry={nodes.Text001.geometry} material={materials.BoardText} position={[157.91, 79.32, 680.94]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Text005" geometry={nodes.Text005.geometry} material={nodes.Text005.material} position={[332.35, 3.47, 459.94]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Text009" geometry={nodes.Text009.geometry} material={nodes.Text009.material} position={[329.25, 30.11, 459.94]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Text026" geometry={nodes.Text026.geometry} material={nodes.Text026.material} position={[336.41, 10.67, 459.89]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Text027" geometry={nodes.Text027.geometry} material={nodes.Text027.material} position={[332.29, 23.73, 459.87]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Text028" geometry={nodes.Text028.geometry} material={nodes.Text028.material} position={[333.49, -6.55, 459.87]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Text029" geometry={nodes.Text029.geometry} material={nodes.Text029.material} position={[330.43, 17.21, 459.87]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cube064" geometry={nodes.Cube064.geometry} material={materials.BoardText} position={[311.69, 21.65, 459.59]} rotation={[0, 0, Math.PI / 2]} />
        <mesh name="Cube065" geometry={nodes.Cube065.geometry} material={materials.BoardText} position={[313.54, -10.55, 459.59]} rotation={[0, 0, 2.46]} />
        <mesh name="Text007" geometry={nodes.Text007.geometry} material={materials.BoardText} position={[156.07, 78.2, -142.11]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Text008" geometry={nodes.Text008.geometry} material={materials.BoardText} position={[156.07, 78.2, -148.55]} rotation={[Math.PI / 2, 0, Math.PI]} />
        <mesh name="Text030" geometry={nodes.Text030.geometry} material={nodes.Text030.material} position={[202.11, -0.21, -617.52]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Text031" geometry={nodes.Text031.geometry} material={nodes.Text031.material} position={[205.35, -16.44, -617.17]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Text032" geometry={nodes.Text032.geometry} material={nodes.Text032.material} position={[202.14, -7.89, -617.55]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Text033" geometry={nodes.Text033.geometry} material={nodes.Text033.material} position={[200.98, -3.88, -617.58]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Text034" geometry={nodes.Text034.geometry} material={nodes.Text034.material} position={[201.9, -11.21, -617.57]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Cube067" geometry={nodes.Cube067.geometry} material={materials.BoardText} position={[217.73, -1.87, -617.51]} />
        <mesh name="Cube068" geometry={nodes.Cube068.geometry} material={materials.BoardText} position={[214.41, -9.02, -617.51]} rotation={[0, 0, Math.PI / 2]} />
        <mesh name="Cube069" geometry={nodes.Cube069.geometry} material={materials.BoardText} position={[190.76, -16.59, -617.51]} rotation={[0, 0, Math.PI]} />
        <mesh name="Text006" geometry={nodes.Text006.geometry} material={materials.BoardText} position={[155.99, 79.32, 674.43]} rotation={[Math.PI / 2, 0, Math.PI]} />
      </group>
    </group>
  )
}

useGLTF.preload('/BuildingHoardingText-transformed.glb')
