/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 BuildingHoardings.glb -T
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function BuildingHoardings(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/BuildingHoardings-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group scale={0.1} ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Cube059" position={[156.1, 78.44, 677.78]}>
          <mesh name="Cube106" geometry={nodes.Cube106.geometry} material={materials.Building_material} />
          <mesh name="Cube106_1" geometry={nodes.Cube106_1.geometry} material={materials.BuildingSignMaterial2} />
        </group>
        <mesh name="Cylinder036" geometry={nodes.Cylinder036.geometry} material={materials.Building_material} position={[107.49, 62.16, 677.79]} rotation={[0, 0, -Math.PI / 2]} />
        <mesh name="Cylinder037" geometry={nodes.Cylinder037.geometry} material={materials.Building_material} position={[107.49, 96.14, 677.79]} rotation={[0, 0, -Math.PI / 2]} />
        <mesh name="Cylinder038" geometry={nodes.Cylinder038.geometry} material={materials.BuildingSignMaterial2} position={[112.91, 100.32, 677.77]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder039" geometry={nodes.Cylinder039.geometry} material={materials.BuildingSignMaterial2} position={[121.72, 100.32, 677.77]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder040" geometry={nodes.Cylinder040.geometry} material={materials.BuildingSignMaterial2} position={[131.54, 100.32, 677.77]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder041" geometry={nodes.Cylinder041.geometry} material={materials.BuildingSignMaterial2} position={[141.49, 100.32, 677.77]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder042" geometry={nodes.Cylinder042.geometry} material={materials.BuildingSignMaterial2} position={[150.44, 100.32, 677.77]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder090" geometry={nodes.Cylinder090.geometry} material={materials.BuildingSignMaterial2} position={[159.67, 100.32, 677.77]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder091" geometry={nodes.Cylinder091.geometry} material={materials.BuildingSignMaterial2} position={[199.46, 100.32, 677.77]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder092" geometry={nodes.Cylinder092.geometry} material={materials.BuildingSignMaterial2} position={[112.91, 56.82, 677.77]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder093" geometry={nodes.Cylinder093.geometry} material={materials.BuildingSignMaterial2} position={[121.72, 56.82, 677.77]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder094" geometry={nodes.Cylinder094.geometry} material={materials.BuildingSignMaterial2} position={[131.54, 56.82, 677.77]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder095" geometry={nodes.Cylinder095.geometry} material={materials.BuildingSignMaterial2} position={[141.49, 56.82, 677.77]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder096" geometry={nodes.Cylinder096.geometry} material={materials.BuildingSignMaterial2} position={[150.44, 56.82, 677.77]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder097" geometry={nodes.Cylinder097.geometry} material={materials.BuildingSignMaterial2} position={[159.67, 56.82, 677.77]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder098" geometry={nodes.Cylinder098.geometry} material={materials.BuildingSignMaterial2} position={[199.46, 56.82, 677.77]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder099" geometry={nodes.Cylinder099.geometry} material={materials.BuildingSignMaterial2} position={[199.46, 65.06, 677.77]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder100" geometry={nodes.Cylinder100.geometry} material={materials.BuildingSignMaterial2} position={[199.46, 73.58, 677.77]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder101" geometry={nodes.Cylinder101.geometry} material={materials.BuildingSignMaterial2} position={[199.46, 91.47, 677.77]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder102" geometry={nodes.Cylinder102.geometry} material={materials.BuildingSignMaterial2} position={[199.46, 83.12, 677.77]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder103" geometry={nodes.Cylinder103.geometry} material={materials.BuildingSignMaterial2} position={[112.89, 65.06, 677.77]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder104" geometry={nodes.Cylinder104.geometry} material={materials.BuildingSignMaterial2} position={[112.89, 73.58, 677.77]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder105" geometry={nodes.Cylinder105.geometry} material={materials.BuildingSignMaterial2} position={[112.89, 91.47, 677.77]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder106" geometry={nodes.Cylinder106.geometry} material={materials.BuildingSignMaterial2} position={[112.89, 83.12, 677.77]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder107" geometry={nodes.Cylinder107.geometry} material={materials.BuildingSignMaterial2} position={[190.87, 100.32, 677.77]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder108" geometry={nodes.Cylinder108.geometry} material={materials.BuildingSignMaterial2} position={[181.16, 100.32, 677.77]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder109" geometry={nodes.Cylinder109.geometry} material={materials.BuildingSignMaterial2} position={[170.19, 100.32, 677.77]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder110" geometry={nodes.Cylinder110.geometry} material={materials.BuildingSignMaterial2} position={[190.87, 56.72, 677.77]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder111" geometry={nodes.Cylinder111.geometry} material={materials.BuildingSignMaterial2} position={[181.16, 56.72, 677.77]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder112" geometry={nodes.Cylinder112.geometry} material={materials.BuildingSignMaterial2} position={[170.19, 56.72, 677.77]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <group name="Cube060" position={[156.1, 78.44, -145.25]}>
          <mesh name="Cube186" geometry={nodes.Cube186.geometry} material={materials.Building_material} />
          <mesh name="Cube186_1" geometry={nodes.Cube186_1.geometry} material={materials.BuildingSignMaterial2} />
        </group>
        <mesh name="Cylinder113" geometry={nodes.Cylinder113.geometry} material={materials.Building_material} position={[107.49, 62.16, -145.24]} rotation={[0, 0, -Math.PI / 2]} />
        <mesh name="Cylinder114" geometry={nodes.Cylinder114.geometry} material={materials.Building_material} position={[107.49, 96.14, -145.24]} rotation={[0, 0, -Math.PI / 2]} />
        <mesh name="Cylinder115" geometry={nodes.Cylinder115.geometry} material={materials.BuildingSignMaterial2} position={[112.91, 100.32, -145.26]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder116" geometry={nodes.Cylinder116.geometry} material={materials.BuildingSignMaterial2} position={[121.72, 100.32, -145.26]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder117" geometry={nodes.Cylinder117.geometry} material={materials.BuildingSignMaterial2} position={[131.54, 100.32, -145.26]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder118" geometry={nodes.Cylinder118.geometry} material={materials.BuildingSignMaterial2} position={[141.49, 100.32, -145.26]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder119" geometry={nodes.Cylinder119.geometry} material={materials.BuildingSignMaterial2} position={[150.44, 100.32, -145.26]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder120" geometry={nodes.Cylinder120.geometry} material={materials.BuildingSignMaterial2} position={[159.67, 100.32, -145.26]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder121" geometry={nodes.Cylinder121.geometry} material={materials.BuildingSignMaterial2} position={[199.46, 100.32, -145.26]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder122" geometry={nodes.Cylinder122.geometry} material={materials.BuildingSignMaterial2} position={[112.91, 56.82, -145.26]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder123" geometry={nodes.Cylinder123.geometry} material={materials.BuildingSignMaterial2} position={[121.72, 56.82, -145.26]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder124" geometry={nodes.Cylinder124.geometry} material={materials.BuildingSignMaterial2} position={[131.54, 56.82, -145.26]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder125" geometry={nodes.Cylinder125.geometry} material={materials.BuildingSignMaterial2} position={[141.49, 56.82, -145.26]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder126" geometry={nodes.Cylinder126.geometry} material={materials.BuildingSignMaterial2} position={[150.44, 56.82, -145.26]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder127" geometry={nodes.Cylinder127.geometry} material={materials.BuildingSignMaterial2} position={[159.67, 56.82, -145.26]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder128" geometry={nodes.Cylinder128.geometry} material={materials.BuildingSignMaterial2} position={[199.46, 56.82, -145.26]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder129" geometry={nodes.Cylinder129.geometry} material={materials.BuildingSignMaterial2} position={[199.46, 65.06, -145.26]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder130" geometry={nodes.Cylinder130.geometry} material={materials.BuildingSignMaterial2} position={[199.46, 73.58, -145.26]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder131" geometry={nodes.Cylinder131.geometry} material={materials.BuildingSignMaterial2} position={[199.46, 91.47, -145.26]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder132" geometry={nodes.Cylinder132.geometry} material={materials.BuildingSignMaterial2} position={[199.46, 83.12, -145.26]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder133" geometry={nodes.Cylinder133.geometry} material={materials.BuildingSignMaterial2} position={[112.89, 65.06, -145.26]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder134" geometry={nodes.Cylinder134.geometry} material={materials.BuildingSignMaterial2} position={[112.89, 73.58, -145.26]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder135" geometry={nodes.Cylinder135.geometry} material={materials.BuildingSignMaterial2} position={[112.89, 91.47, -145.26]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder136" geometry={nodes.Cylinder136.geometry} material={materials.BuildingSignMaterial2} position={[112.89, 83.12, -145.26]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder137" geometry={nodes.Cylinder137.geometry} material={materials.BuildingSignMaterial2} position={[190.87, 100.32, -145.26]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder138" geometry={nodes.Cylinder138.geometry} material={materials.BuildingSignMaterial2} position={[181.16, 100.32, -145.26]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder139" geometry={nodes.Cylinder139.geometry} material={materials.BuildingSignMaterial2} position={[170.19, 100.32, -145.26]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder140" geometry={nodes.Cylinder140.geometry} material={materials.BuildingSignMaterial2} position={[190.87, 56.72, -145.26]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder141" geometry={nodes.Cylinder141.geometry} material={materials.BuildingSignMaterial2} position={[181.16, 56.72, -145.26]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <mesh name="Cylinder142" geometry={nodes.Cylinder142.geometry} material={materials.BuildingSignMaterial2} position={[170.19, 56.72, -145.26]} rotation={[-Math.PI / 2, 1.57, 0]} />
        <group name="Cube061" position={[330.46, 6.5, 457.96]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh name="Cube188" geometry={nodes.Cube188.geometry} material={materials.Building_material} />
          <mesh name="Cube188_1" geometry={nodes.Cube188_1.geometry} material={materials.BuildingSignMaterial2} />
        </group>
        <mesh name="Cylinder143" geometry={nodes.Cylinder143.geometry} material={materials.Building_material} position={[347.94, -36.85, 458.19]} rotation={[0, 0, -Math.PI]} />
        <mesh name="Cylinder144" geometry={nodes.Cylinder144.geometry} material={materials.Building_material} position={[310.13, -36.85, 458.19]} rotation={[0, 0, -Math.PI]} />
        <group name="Cube062" position={[203.34, -9.19, -619.31]}>
          <mesh name="Cube216" geometry={nodes.Cube216.geometry} material={materials.Building_material} />
          <mesh name="Cube216_1" geometry={nodes.Cube216_1.geometry} material={materials.BuildingSignMaterial2} />
        </group>
        <mesh name="Cylinder145" geometry={nodes.Cylinder145.geometry} material={materials.Building_material} position={[221.42, -36.85, -619.04]} rotation={[0, 0, -Math.PI]} />
        <mesh name="Cylinder146" geometry={nodes.Cylinder146.geometry} material={materials.Building_material} position={[186.73, -36.85, -619.04]} rotation={[0, 0, -Math.PI]} />
      </group>
    </group>
  )
}

useGLTF.preload('/BuildingHoardings-transformed.glb')
