/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 CRC.glb -T
*/

import { useAnimations, useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'

export function CRC(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/CRC-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group scale={0.1} ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Cube288" geometry={nodes.Cube288.geometry} material={materials['Building_material.002']} position={[-1609.08, 280.87, 568.27]} rotation={[0, -Math.PI / 2, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/CRC-transformed.glb')
