/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Cultural_Technical_Text.glb -T
*/

import { useAnimations, useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'

export function Cultural_Technical_Text(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Cultural_Technical_Text-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group scale={0.1} ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Text025" geometry={nodes.Text025.geometry} material={materials.Neon_text3} position={[32.99, 56.94, -148.54]} rotation={[Math.PI / 2, 0, Math.PI]} />
        <mesh name="Text024" geometry={nodes.Text024.geometry} material={materials.Neon_text3} position={[31.43, 58.75, 673.07]} rotation={[Math.PI / 2, 0, Math.PI]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Cultural_Technical_Text-transformed.glb')
