/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Doors.glb -T
*/

import { useAnimations, useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'

export function Doors(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Doors-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group scale={0.1} ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="10901_Closet_doors_v3_L3" geometry={nodes['10901_Closet_doors_v3_L3'].geometry} material={materials['_10901_Closet_doors_v3_null_.001']} position={[38.13, -20.3, 670.17]} rotation={[-3.1, 0, 0]} scale={[0.35, 0.2, 0.2]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Doors-transformed.glb')
