/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 EmitBodies.glb -T
*/

import { Sparkles, useAnimations, useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'
export function EmitBodies(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/EmitBodies-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    
    <group scale={0.1} ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Neon1001" geometry={nodes.Neon1001.geometry} material={materials.Checkpoint_in_neon} position={[271.27, -17.21, 1879.25]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Neon1002" geometry={nodes.Neon1002.geometry} material={materials.Checkpoint_in_neon} position={[525.61, -17.21, 1878.67]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Neon1003" geometry={nodes.Neon1003.geometry} material={materials.Checkpoint_in_neon} position={[398.05, 51.52, 1878.77]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
        <mesh name="Neon1004" geometry={nodes.Neon1004.geometry} material={materials.Checkpoint_in_neon} position={[380.45, -17.21, 1878.67]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Neon1005" geometry={nodes.Neon1005.geometry} material={materials.Checkpoint_in_neon} position={[423.08, -17.21, 1878.67]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Neon1006" geometry={nodes.Neon1006.geometry} material={materials.Checkpoint_in_neon} position={[398.05, 75.11, 1878.77]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
        <mesh name="Neon176001" geometry={nodes.Neon176001.geometry} material={materials.Neon} position={[-1626.93, 395.58, 361.45]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Neon176002" geometry={nodes.Neon176002.geometry} material={materials.Neon} position={[-1626.93, 395.58, 779.43]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Neon176003" geometry={nodes.Neon176003.geometry} material={materials.Neon} position={[-1406.55, 395.58, 572.61]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Neon176004" geometry={nodes.Neon176004.geometry} material={materials.Neon} position={[-1855.24, 395.58, 572.61]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Neon176005" geometry={nodes.Neon176005.geometry} material={materials.Neon} position={[-1855.24, 260.26, 363.24]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
        <mesh name="Neon176006" geometry={nodes.Neon176006.geometry} material={materials.Neon} position={[-1855.24, 260.26, 781.31]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
        <mesh name="Neon176007" geometry={nodes.Neon176007.geometry} material={materials.Neon} position={[-1406.05, 260.26, 363.24]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
        <mesh name="Neon176008" geometry={nodes.Neon176008.geometry} material={materials.Neon} position={[-1406.05, 260.26, 781.1]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
        <mesh name="Neon176009" geometry={nodes.Neon176009.geometry} material={materials.Neon} position={[-1291.06, 291.11, 480.25]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
        <mesh name="Neon176010" geometry={nodes.Neon176010.geometry} material={materials.Neon} position={[-1291.06, 291.11, 577.37]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
        <mesh name="Neon176011" geometry={nodes.Neon176011.geometry} material={materials.Neon} position={[-1406.39, 291.11, 577.37]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
        <mesh name="Neon176012" geometry={nodes.Neon176012.geometry} material={materials.Neon} position={[-1407.5, 465.36, 528.91]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Neon176013" geometry={nodes.Neon176013.geometry} material={materials.Neon} position={[-1290.48, 465.6, 528.91]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Neon176014" geometry={nodes.Neon176014.geometry} material={materials.Neon} position={[-1346.42, 465.42, 579.26]} rotation={[0, -1.57, 0]} />
        <mesh name="Neon176015" geometry={nodes.Neon176015.geometry} material={materials.Neon} position={[-1346.42, 465.42, 480.8]} rotation={[0, -1.57, 0]} />
        <mesh name="Neon176016" geometry={nodes.Neon176016.geometry} material={materials.Neon} position={[-1406.48, 291.11, 480.25]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
        <mesh name="Lab2_windows_1031" geometry={nodes.Lab2_windows_1031.geometry} material={materials.Fake_windows} position={[-1405.3, 357.63, 716.74]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Lab2_windows_1032" geometry={nodes.Lab2_windows_1032.geometry} material={materials.Fake_windows} position={[-1405.3, 277.51, 716.74]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Lab2_windows_1033" geometry={nodes.Lab2_windows_1033.geometry} material={materials.Fake_windows} position={[-1405.3, 195.65, 716.74]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Lab2_windows_1034" geometry={nodes.Lab2_windows_1034.geometry} material={materials.Fake_windows} position={[-1404.89, 188.43, 646.44]} rotation={[-Math.PI, 1.56, -Math.PI]} />
        <mesh name="Lab2_windows_1035" geometry={nodes.Lab2_windows_1035.geometry} material={materials.Fake_windows} position={[-1404.89, 278.48, 646.44]} rotation={[-Math.PI, 1.56, -Math.PI]} />
        <mesh name="Lab2_windows_1036" geometry={nodes.Lab2_windows_1036.geometry} material={materials.Fake_windows} position={[-1404.89, 354.93, 646.44]} rotation={[-Math.PI, 1.56, -Math.PI]} />
        
    
        <mesh name="Torus" geometry={nodes.Torus.geometry} material={materials['Street Light']} position={[323.82, 36.56, 678.54]} />
        <mesh name="Torus001" geometry={nodes.Torus001.geometry} material={materials['Street Light']} position={[323.82, 36.56, 239.12]} />
        <Sparkles  position={[323.82, 33, 239.12]} scale={25} size={10} count={100} />
        <mesh name="Torus002" geometry={nodes.Torus002.geometry} material={materials['Street Light']} position={[562.09, -3.36, 61.97]} />
        <Sparkles  position={[562.09, -3.36, 61.97]} scale={25} size={10} count={100} speed={2}/>
        <mesh name="Torus003" geometry={nodes.Torus003.geometry} material={materials['Street Light']} position={[255.56, 39.52, -512.78]} />
        <Sparkles  position={[255.56, 39.52, -512.78]} scale={25} size={10} count={100} />        
        <mesh name="Torus004" geometry={nodes.Torus004.geometry} material={materials['Street Light']} position={[113.1, 39.52, -1280.65]} />
        <mesh name="Torus005" geometry={nodes.Torus005.geometry} material={materials['Street Light']} position={[113.1, 39.52, -1685.1]} />
        <mesh name="Torus006" geometry={nodes.Torus006.geometry} material={materials['Street Light']} position={[113.1, 39.52, -2334.41]} />
        <mesh name="Torus007" geometry={nodes.Torus007.geometry} material={materials['Street Light']} position={[483.29, -6.3, -2405.57]} />
        <mesh name="Torus008" geometry={nodes.Torus008.geometry} material={materials['Street Light']} position={[483.29, -6.3, -1648.2]} />
        <mesh name="Torus009" geometry={nodes.Torus009.geometry} material={materials['Street Light']} position={[483.29, -6.3, -1014.44]} />
        <mesh name="Torus010" geometry={nodes.Torus010.geometry} material={materials['Street Light']} position={[951.29, -3.36, -386.02]} />
        <mesh name="Torus011" geometry={nodes.Torus011.geometry} material={materials['Street Light']} position={[951.29, -3.36, 424.92]} />
        <mesh name="Torus012" geometry={nodes.Torus012.geometry} material={materials['Street Light']} position={[-455.61, -2.77, 1046.28]} />
        <mesh name="Torus013" geometry={nodes.Torus013.geometry} material={materials['Street Light']} position={[851.26, -2.77, 1154.56]} />
        <mesh name="Torus014" geometry={nodes.Torus014.geometry} material={materials['Street Light']} position={[-1505.49, 213.73, 241.49]} />
        <mesh name="Torus015" geometry={nodes.Torus015.geometry} material={materials['Street Light']} position={[-1505.49, 213.73, -370.24]} />

        
        <mesh name="Lab2_windows_1010" geometry={nodes.Lab2_windows_1010.geometry} material={materials.Fake_windows} position={[666.82, 3.57, -2809.21]} rotation={[Math.PI, -0.01, Math.PI]} />
        <mesh name="Lab2_windows_1011" geometry={nodes.Lab2_windows_1011.geometry} material={materials.Fake_windows} position={[1059.41, 17.34, -2808.21]} rotation={[Math.PI, -0.01, Math.PI]} />
        <mesh name="Lab2_windows_1023" geometry={nodes.Lab2_windows_1023.geometry} material={materials.Fake_windows} position={[1059.41, 17.61, -2497.5]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh name="Lab2_windows_1024" geometry={nodes.Lab2_windows_1024.geometry} material={materials.Fake_windows} position={[666.82, 3.57, -2497.49]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Lab2_windows_1049" geometry={nodes.Lab2_windows_1049.geometry} material={materials.Fake_windows} position={[1059.41, 91.71, -2497.5]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh name="Lab2_windows_1050" geometry={nodes.Lab2_windows_1050.geometry} material={materials.Fake_windows} position={[666.82, 77.67, -2497.49]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Lab2_windows_1051" geometry={nodes.Lab2_windows_1051.geometry} material={materials.Fake_windows} position={[666.82, 70.19, -2809.21]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Lab2_windows_1052" geometry={nodes.Lab2_windows_1052.geometry} material={materials.Fake_windows} position={[1059.41, 83.97, -2808.21]} rotation={[Math.PI, -0.01, Math.PI]} />
        <mesh name="Lab2_windows_1012" geometry={nodes.Lab2_windows_1012.geometry} material={materials.Fake_windows} position={[580.88, -28.52, -2808.21]} rotation={[Math.PI, -0.01, Math.PI]} />
        <mesh name="Lab2_windows_1021" geometry={nodes.Lab2_windows_1021.geometry} material={materials.Fake_windows} position={[1059.41, 17.61, -1722.05]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh name="Lab2_windows_1022" geometry={nodes.Lab2_windows_1022.geometry} material={materials.Fake_windows} position={[666.82, 3.57, -1723.12]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Lab2_windows_1055" geometry={nodes.Lab2_windows_1055.geometry} material={materials.Fake_windows} position={[1059.41, 93.49, -1722.05]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh name="Lab2_windows_1056" geometry={nodes.Lab2_windows_1056.geometry} material={materials.Fake_windows} position={[666.82, 79.45, -1723.12]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Lab2_windows_1016" geometry={nodes.Lab2_windows_1016.geometry} material={materials.Fake_windows} position={[666.82, 3.57, -1328.57]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Lab2_windows_1017" geometry={nodes.Lab2_windows_1017.geometry} material={materials.Fake_windows} position={[1059.41, 17.61, -1329.26]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh name="Lab2_windows_1018" geometry={nodes.Lab2_windows_1018.geometry} material={materials.Fake_windows} position={[580.88, -27, -1329.2]} rotation={[Math.PI, -0.01, Math.PI]} />
        <mesh name="Lab2_windows_1019" geometry={nodes.Lab2_windows_1019.geometry} material={materials.Fake_windows} position={[1059.41, 17.61, -1017.96]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh name="Lab2_windows_1020" geometry={nodes.Lab2_windows_1020.geometry} material={materials.Fake_windows} position={[666.82, 3.57, -1017.98]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Lab2_windows_1057" geometry={nodes.Lab2_windows_1057.geometry} material={materials.Fake_windows} position={[1059.41, 92.29, -1017.96]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh name="Lab2_windows_1058" geometry={nodes.Lab2_windows_1058.geometry} material={materials.Fake_windows} position={[666.82, 78.25, -1017.98]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Lab2_windows_1059" geometry={nodes.Lab2_windows_1059.geometry} material={materials.Fake_windows} position={[666.82, 80.7, -1328.57]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Lab2_windows_1060" geometry={nodes.Lab2_windows_1060.geometry} material={materials.Fake_windows} position={[1059.41, 94.74, -1329.26]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh name="Neon147" geometry={nodes.Neon147.geometry} material={materials.Neon_text2} position={[885.41, 34.55, -619.25]} rotation={[0, 1.55, -1.58]} />
        <mesh name="Neon148" geometry={nodes.Neon148.geometry} material={materials.Neon_text2} position={[885.41, 34.56, -740.26]} rotation={[0, 1.55, -1.58]} />
        <mesh name="Neon149" geometry={nodes.Neon149.geometry} material={materials.Neon_text2} position={[1179.27, 40.85, -615.03]} rotation={[-1.51, 0.57, 1.56]} />
        <mesh name="Neon150" geometry={nodes.Neon150.geometry} material={materials.Neon_text2} position={[1178.69, 39.96, -734.85]} rotation={[-1.53, 0.57, 1.56]} />
        <mesh name="Neon151" geometry={nodes.Neon151.geometry} material={materials.Neon_text2} position={[885.41, 53.68, -739.64]} rotation={[0, 1.55, -1.58]} />
        <mesh name="Neon152" geometry={nodes.Neon152.geometry} material={materials.Neon_text2} position={[885.16, 54.33, -620.9]} rotation={[0, 1.55, -1.58]} />
        <mesh name="Neon153" geometry={nodes.Neon153.geometry} material={materials.Neon_text2} position={[563.28, 40.73, -615.67]} rotation={[-1.53, 0.57, 1.56]} />
        <mesh name="Neon154" geometry={nodes.Neon154.geometry} material={materials.Neon_text2} position={[563.8, 40.73, -735.31]} rotation={[-1.53, 0.57, 1.56]} />
        <mesh name="Neon155" geometry={nodes.Neon155.geometry} material={materials.Neon_text2} position={[1178.77, 62.63, -709.02]} rotation={[-0.33, 0.31, 1.48]} />
        <mesh name="Neon156" geometry={nodes.Neon156.geometry} material={materials.Neon_text2} position={[1177.61, 61.85, -649.86]} rotation={[-2.81, -0.35, -1.64]} />
        <mesh name="Neon157" geometry={nodes.Neon157.geometry} material={materials.Neon_text2} position={[564.93, 62.23, -708.57]} rotation={[-0.33, 0.31, 1.48]} />
        <mesh name="Neon158" geometry={nodes.Neon158.geometry} material={materials.Neon_text2} position={[563.77, 63.02, -649.86]} rotation={[-2.81, -0.35, -1.64]} />
        <mesh name="Neon159" geometry={nodes.Neon159.geometry} material={materials.Neon_text2} position={[885.41, 11.46, -560.97]} rotation={[0, 1.55, -1.58]} />
        <mesh name="Neon160" geometry={nodes.Neon160.geometry} material={materials.Neon_text2} position={[563.77, 19.31, -589.76]} rotation={[-2.81, -0.35, -1.64]} />
        <mesh name="Neon161" geometry={nodes.Neon161.geometry} material={materials.Neon_text2} position={[564.94, 19.31, -767.99]} rotation={[-0.33, 0.33, 1.49]} />
        <mesh name="Neon162" geometry={nodes.Neon162.geometry} material={materials.Neon_text2} position={[885.41, 11.73, -798.74]} rotation={[0, 1.55, -1.58]} />
        <mesh name="Neon164" geometry={nodes.Neon164.geometry} material={materials.Neon_text2} position={[1179.05, 19.31, -767.99]} rotation={[-0.33, 0.33, 1.49]} />
        <mesh name="Neon165" geometry={nodes.Neon165.geometry} material={materials.Neon_text2} position={[1179.03, 19.31, -589.76]} rotation={[-2.81, -0.35, -1.64]} />
        <mesh name="Neon166" geometry={nodes.Neon166.geometry} material={materials.Neon_text2} position={[885.41, 77.83, -681.34]} rotation={[0, 1.55, -1.58]} />
        <mesh name="Neon167" geometry={nodes.Neon167.geometry} material={materials.Neon_text2} position={[563.44, -38.62, -560.07]} rotation={[-1.56, 0.39, 1.57]} />
        <mesh name="Neon168" geometry={nodes.Neon168.geometry} material={materials.Neon_text2} position={[566.09, -38.62, -798.8]} rotation={[-1.56, 0.39, 1.57]} />
        <mesh name="Neon170" geometry={nodes.Neon170.geometry} material={materials.Neon_text2} position={[1179.88, -38.62, -559.66]} rotation={[-1.56, 0.39, 1.57]} />
        <mesh name="Neon169" geometry={nodes.Neon169.geometry} material={materials.Neon_text2} position={[1179.88, -38.62, -798.8]} rotation={[-1.56, 0.39, 1.57]} />
        <mesh name="Neon171" geometry={nodes.Neon171.geometry} material={materials.Neon} position={[1082.9, 38.94, 737.68]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Neon172" geometry={nodes.Neon172.geometry} material={materials.Neon} position={[1022.2, 38.94, 1010.87]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Neon173" geometry={nodes.Neon173.geometry} material={materials.Neon} position={[1260.72, 38.94, 875.12]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Neon174" geometry={nodes.Neon174.geometry} material={materials.Neon} position={[1260.78, -30.27, 1011.12]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
        <mesh name="Neon175" geometry={nodes.Neon175.geometry} material={materials.Neon} position={[1260.78, -30.27, 737.85]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
        <mesh name="Neon176" geometry={nodes.Neon176.geometry} material={materials.Neon} position={[711.36, 38.94, 479.11]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Neon177" geometry={nodes.Neon177.geometry} material={materials.Neon} position={[904.01, 38.94, 610.6]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Neon178" geometry={nodes.Neon178.geometry} material={materials.Neon} position={[774.16, 38.94, 875.12]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Neon179" geometry={nodes.Neon179.geometry} material={materials.Neon} position={[515.99, 38.94, 609.61]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Neon180" geometry={nodes.Neon180.geometry} material={materials.Neon} position={[646.65, 38.94, 738.9]} rotation={[0, -1.57, 0]} />
        <mesh name="Neon182" geometry={nodes.Neon182.geometry} material={materials.Neon} position={[773.1, -25.73, 739.94]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
        <mesh name="Neon183" geometry={nodes.Neon183.geometry} material={materials.Neon} position={[511.93, -25.73, 739.21]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
        <mesh name="Neon184" geometry={nodes.Neon184.geometry} material={materials.Neon} position={[513, -25.73, 480.4]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
        <mesh name="Neon181" geometry={nodes.Neon181.geometry} material={materials.Neon} position={[774.16, -25.73, 1011.77]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
        <mesh name="Cube522" geometry={nodes.Cube522.geometry} material={materials['Street Light.001']} position={[980.92, 70.82, -3350.66]} rotation={[0, 1.56, -0.42]} />
        <mesh name="Cube524" geometry={nodes.Cube524.geometry} material={materials['Street Light.001']} position={[562.6, 70.82, -3393.32]} rotation={[0, -0.01, -0.42]} />
        <mesh name="Cube526" geometry={nodes.Cube526.geometry} material={materials['Street Light.001']} position={[259.68, 70.82, -3393.05]} rotation={[Math.PI, 0.01, 2.72]} />
        <mesh name="Cube535" geometry={nodes.Cube535.geometry} material={materials['Street Light.001']} position={[-194.34, 100.23, -3337.9]} rotation={[0, 1.56, -0.42]} />
        <mesh name="Cube537" geometry={nodes.Cube537.geometry} material={materials['Street Light.001']} position={[-849.31, 110.83, -3319.75]} rotation={[Math.PI, 1.24, 2.72]} />
        <mesh name="Cube559" geometry={nodes.Cube559.geometry} material={materials['Street Light.001']} position={[-492.19, 110.83, -3340.07]} rotation={[3.14, 1.57, 2.72]} />
        <mesh name="Cube561" geometry={nodes.Cube561.geometry} material={materials['Street Light.001']} position={[-943.28, 106.41, -2942.7]} rotation={[Math.PI, 0.01, 2.72]} />
        <mesh name="Cube563" geometry={nodes.Cube563.geometry} material={materials['Street Light.001']} position={[-943.28, 106.41, -2451.72]} rotation={[Math.PI, 0.01, 2.72]} />
        <mesh name="Cube565" geometry={nodes.Cube565.geometry} material={materials['Street Light.001']} position={[-943.28, 106.41, -1847.65]} rotation={[Math.PI, 0.01, 2.72]} />
        <mesh name="Cube567" geometry={nodes.Cube567.geometry} material={materials['Street Light.001']} position={[-943.28, 106.41, -1163.66]} rotation={[Math.PI, 0.01, 2.72]} />
        <mesh name="Cube569" geometry={nodes.Cube569.geometry} material={materials['Street Light.001']} position={[-943.28, 106.41, -325.29]} rotation={[Math.PI, 0.01, 2.72]} />
        <mesh name="Cube571" geometry={nodes.Cube571.geometry} material={materials['Street Light.001']} position={[-943.28, 106.41, 317.09]} rotation={[Math.PI, 0.01, 2.72]} />
        <mesh name="Cube573" geometry={nodes.Cube573.geometry} material={materials['Street Light.001']} position={[-943.28, 106.41, 881.55]} rotation={[Math.PI, 0.01, 2.72]} />
        <mesh name="Cube575" geometry={nodes.Cube575.geometry} material={materials['Street Light.001']} position={[-112.34, 58.16, 1238.09]} rotation={[0, -0.01, -0.42]} />
        <mesh name="Cube577" geometry={nodes.Cube577.geometry} material={materials['Street Light.001']} position={[525.67, 58.16, 1252.39]} rotation={[0, -0.01, -0.42]} />
        <mesh name="Cube579" geometry={nodes.Cube579.geometry} material={materials['Street Light.001']} position={[-1291.25, 211.58, -1023.02]} rotation={[0, -0.53, -0.42]} />
        <mesh name="Cube306" geometry={nodes.Cube306.geometry} material={materials['Street Light.001']} position={[1504.78, 70.82, 956.22]} rotation={[0, 0, -0.42]} />
        <mesh name="Cube431" geometry={nodes.Cube431.geometry} material={materials['Street Light.001']} position={[1487.26, 70.82, 314.58]} rotation={[0, 0, -0.42]} />
        <mesh name="Cube501" geometry={nodes.Cube501.geometry} material={materials['Street Light.001']} position={[1472.32, 70.82, -402.98]} rotation={[0, 0, -0.42]} />
        <mesh name="Cube508" geometry={nodes.Cube508.geometry} material={materials['Street Light.001']} position={[1459, 70.82, -1079.18]} rotation={[0, 0, -0.42]} />
        <mesh name="Cube516" geometry={nodes.Cube516.geometry} material={materials['Street Light.001']} position={[1442.79, 70.82, -1893.95]} rotation={[0, 0, -0.42]} />
        <mesh name="Cube518" geometry={nodes.Cube518.geometry} material={materials['Street Light.001']} position={[1447.78, 70.82, -2642.03]} rotation={[0, 0, -0.42]} />
        <mesh name="Cube520" geometry={nodes.Cube520.geometry} material={materials['Street Light.001']} position={[1363.54, 70.82, -3204.49]} rotation={[0, 0.67, -0.42]} />
        <mesh name="Lab2_windows_1013" geometry={nodes.Lab2_windows_1013.geometry} material={materials.Fake_windows} position={[666.82, 3.57, -2033.37]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Lab2_windows_1014" geometry={nodes.Lab2_windows_1014.geometry} material={materials.Fake_windows} position={[1059.41, 16.75, -2033.02]} rotation={[Math.PI, -0.01, Math.PI]} />
        <mesh name="Lab2_windows_1015" geometry={nodes.Lab2_windows_1015.geometry} material={materials.Fake_windows} position={[580.88, -26.91, -2033.91]} rotation={[Math.PI, -0.01, Math.PI]} />
        <mesh name="Lab2_windows_1053" geometry={nodes.Lab2_windows_1053.geometry} material={materials.Fake_windows} position={[666.82, 70.46, -2033.37]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Lab2_windows_1054" geometry={nodes.Lab2_windows_1054.geometry} material={materials.Fake_windows} position={[1059.41, 83.63, -2033.02]} rotation={[Math.PI, -0.01, Math.PI]} />
        <mesh name="Lab2_windows_1007" geometry={nodes.Lab2_windows_1007.geometry} material={materials.Fake_windows} position={[-112.83, 39.05, -2659.04]} />
        <mesh name="Lab2_windows_1008" geometry={nodes.Lab2_windows_1008.geometry} material={materials.Fake_windows} position={[-505.43, 50.94, -2660.05]} rotation={[0, 0.01, 0]} />
        <mesh name="Lab2_windows_1009" geometry={nodes.Lab2_windows_1009.geometry} material={materials.Fake_windows} position={[-26.89, 6.96, -2660.05]} rotation={[0, 0.01, 0]} />
        <mesh name="Lab2_windows_1025" geometry={nodes.Lab2_windows_1025.geometry} material={materials.Fake_windows} position={[-112.83, 37.74, -2969.95]} />
        <mesh name="Lab2_windows_1026" geometry={nodes.Lab2_windows_1026.geometry} material={materials.Fake_windows} position={[-505.43, 50.94, -2970.92]} rotation={[0, 0.01, 0]} />
        <mesh name="Lab2_windows_1045" geometry={nodes.Lab2_windows_1045.geometry} material={materials.Fake_windows} position={[-112.83, 117.22, -2659.04]} />
        <mesh name="Lab2_windows_1046" geometry={nodes.Lab2_windows_1046.geometry} material={materials.Fake_windows} position={[-505.43, 129.12, -2660.05]} rotation={[0, 0.01, 0]} />
        <mesh name="Lab2_windows_1047" geometry={nodes.Lab2_windows_1047.geometry} material={materials.Fake_windows} position={[-112.83, 109.25, -2969.95]} />
        <mesh name="Lab2_windows_1048" geometry={nodes.Lab2_windows_1048.geometry} material={materials.Fake_windows} position={[-505.43, 122.45, -2970.92]} rotation={[0, 0.01, 0]} />
        <mesh name="Neon90" geometry={nodes.Neon90.geometry} material={materials.Neon_text5} position={[-83.53, 56.11, -2659.06]} rotation={[1.59, 0, -0.01]} />
        <mesh name="Neon91" geometry={nodes.Neon91.geometry} material={materials.Neon_text5} position={[-83.06, 163.55, -2820.43]} rotation={[-3.12, 0, -0.01]} />
        <mesh name="Neon92" geometry={nodes.Neon92.geometry} material={materials.Neon_text5} position={[-83.53, 53.59, -2971.84]} rotation={[1.59, 0, -0.01]} />
        <mesh name="Neon93" geometry={nodes.Neon93.geometry} material={materials.Neon_text5} position={[-83.53, 194.29, -2879.27]} rotation={[-1.55, 0, -0.01]} />
        <mesh name="Neon97" geometry={nodes.Neon97.geometry} material={materials.Neon_text5} position={[-174.05, 194.29, -2879.27]} rotation={[-1.55, 0, -0.01]} />
        <mesh name="Neon98" geometry={nodes.Neon98.geometry} material={materials.Neon_text5} position={[-174.05, 94.51, -2970.23]} rotation={[-1.55, 0, -0.01]} />
        <mesh name="Neon99" geometry={nodes.Neon99.geometry} material={materials.Neon_text5} position={[-550.67, 61.77, -2970.23]} rotation={[-1.55, 0, -0.01]} />
        <mesh name="Neon100" geometry={nodes.Neon100.geometry} material={materials.Neon_text5} position={[-553.2, 164.68, -2821.04]} rotation={[-3.12, 0, -0.01]} />
        <mesh name="Neon101" geometry={nodes.Neon101.geometry} material={materials.Neon_text5} position={[-553.39, 56.11, -2659.06]} rotation={[1.59, 0, -0.01]} />
        <mesh name="Neon102" geometry={nodes.Neon102.geometry} material={materials.Neon_text5} position={[-326.18, 168.04, -2659.06]} rotation={[-Math.PI, -1.55, 1.57]} />
        <mesh name="Neon103" geometry={nodes.Neon103.geometry} material={materials.Neon_text5} position={[-326.18, 168.04, -2971.57]} rotation={[-Math.PI, -1.55, 1.57]} />
        <mesh name="Neon104" geometry={nodes.Neon104.geometry} material={materials.Neon_text5} position={[-83.53, 60.93, -2739.98]} rotation={[-3.12, -0.01, -0.01]} />
        <mesh name="Neon105" geometry={nodes.Neon105.geometry} material={materials.Neon_text5} position={[30.8, 60.93, -2739.98]} rotation={[-3.12, -0.01, -0.01]} />
        <mesh name="Neon187" geometry={nodes.Neon187.geometry} material={materials.Neon_text5} position={[-29.9, 60.93, -2658.51]} rotation={[-1.19, -1.55, 1.94]} />
        <mesh name="Neon106" geometry={nodes.Neon106.geometry} material={materials.Neon_text5} position={[-29.9, 60.93, -2809.02]} rotation={[-1.19, -1.55, 1.94]} />
        <mesh name="Neon107" geometry={nodes.Neon107.geometry} material={materials.Neon_text5} position={[30.8, -7.49, -2658.98]} rotation={[-1.55, -0.01, -0.01]} />
        <mesh name="Neon108" geometry={nodes.Neon108.geometry} material={materials.Neon_text5} position={[30.8, -7.49, -2809.78]} rotation={[-1.55, -0.01, -0.01]} />
        <mesh name="Neon109" geometry={nodes.Neon109.geometry} material={materials.Neon_text5} position={[-83.53, 224.35, -2926.51]} rotation={[-3.12, 0, -0.01]} />
        <mesh name="Neon110" geometry={nodes.Neon110.geometry} material={materials.Neon_text5} position={[-129.26, 224.35, -2877.92]} rotation={[-1.57, -1.55, 1.57]} />
        <mesh name="Neon111" geometry={nodes.Neon111.geometry} material={materials.Neon_text5} position={[-174.45, 224.35, -2926.86]} rotation={[-3.12, 0, -0.01]} />
        <mesh name="Neon112" geometry={nodes.Neon112.geometry} material={materials.Neon_text5} position={[-129.26, 224.35, -2970.27]} rotation={[-1.57, -1.55, 1.57]} />
        <mesh name="Lab2_windows_1004" geometry={nodes.Lab2_windows_1004.geometry} material={materials.Fake_windows} position={[-112.83, 39.05, -1888.22]} />
        <mesh name="Lab2_windows_1005" geometry={nodes.Lab2_windows_1005.geometry} material={materials.Fake_windows} position={[-505.43, 50.94, -1889.23]} rotation={[0, 0.01, 0]} />
        <mesh name="Lab2_windows_1006" geometry={nodes.Lab2_windows_1006.geometry} material={materials.Fake_windows} position={[-26.89, 6.96, -1889.23]} rotation={[0, 0.01, 0]} />
        <mesh name="Lab2_windows_1027" geometry={nodes.Lab2_windows_1027.geometry} material={materials.Fake_windows} position={[-112.83, 37.74, -2199.26]} />
        <mesh name="Lab2_windows_1028" geometry={nodes.Lab2_windows_1028.geometry} material={materials.Fake_windows} position={[-505.43, 50.94, -2200.21]} rotation={[0, 0.01, 0]} />
        <mesh name="Lab2_windows_1041" geometry={nodes.Lab2_windows_1041.geometry} material={materials.Fake_windows} position={[-112.83, 109.44, -2199.26]} />
        <mesh name="Lab2_windows_1042" geometry={nodes.Lab2_windows_1042.geometry} material={materials.Fake_windows} position={[-505.43, 122.63, -2200.21]} rotation={[0, 0.01, 0]} />
        <mesh name="Lab2_windows_1043" geometry={nodes.Lab2_windows_1043.geometry} material={materials.Fake_windows} position={[-112.83, 113.36, -1888.22]} />
        <mesh name="Lab2_windows_1044" geometry={nodes.Lab2_windows_1044.geometry} material={materials.Fake_windows} position={[-505.43, 125.25, -1889.23]} rotation={[0, 0.01, 0]} />
        <mesh name="Neon41" geometry={nodes.Neon41.geometry} material={materials.Neon_text4} position={[-83.53, 56.11, -1888.57]} rotation={[1.59, 0, -0.01]} />
        <mesh name="Neon42" geometry={nodes.Neon42.geometry} material={materials.Neon_text4} position={[-83.06, 163.55, -2049.93]} rotation={[-3.12, 0, -0.01]} />
        <mesh name="Neon43" geometry={nodes.Neon43.geometry} material={materials.Neon_text4} position={[-83.53, 53.59, -2201.35]} rotation={[1.59, 0, -0.01]} />
        <mesh name="Neon45" geometry={nodes.Neon45.geometry} material={materials.Neon_text4} position={[-174.05, 194.29, -2108.78]} rotation={[-1.55, 0, -0.01]} />
        <mesh name="Neon46" geometry={nodes.Neon46.geometry} material={materials.Neon_text4} position={[-174.05, 94.51, -2199.74]} rotation={[-1.55, 0, -0.01]} />
        <mesh name="Neon47" geometry={nodes.Neon47.geometry} material={materials.Neon_text4} position={[-550.67, 61.77, -2199.74]} rotation={[-1.55, 0, -0.01]} />
        <mesh name="Neon48" geometry={nodes.Neon48.geometry} material={materials.Neon_text4} position={[-553.2, 164.68, -2050.55]} rotation={[-3.12, 0, -0.01]} />
        <mesh name="Neon49" geometry={nodes.Neon49.geometry} material={materials.Neon_text4} position={[-553.39, 56.11, -1888.57]} rotation={[1.59, 0, -0.01]} />
        <mesh name="Neon50" geometry={nodes.Neon50.geometry} material={materials.Neon_text4} position={[-326.18, 168.04, -1888.57]} rotation={[-Math.PI, -1.55, 1.57]} />
        <mesh name="Neon51" geometry={nodes.Neon51.geometry} material={materials.Neon_text4} position={[-326.18, 168.04, -2201.08]} rotation={[-Math.PI, -1.55, 1.57]} />
        <mesh name="Neon80" geometry={nodes.Neon80.geometry} material={materials.Neon_text4} position={[-83.53, 60.93, -1969.49]} rotation={[-3.12, -0.01, -0.01]} />
        <mesh name="Neon81" geometry={nodes.Neon81.geometry} material={materials.Neon_text4} position={[30.8, 60.93, -1969.49]} rotation={[-3.12, -0.01, -0.01]} />
        <mesh name="Neon82" geometry={nodes.Neon82.geometry} material={materials.Neon_text4} position={[-29.9, 60.93, -1888.02]} rotation={[-1.19, -1.55, 1.94]} />
        <mesh name="Neon83" geometry={nodes.Neon83.geometry} material={materials.Neon_text4} position={[-29.9, 60.93, -2038.52]} rotation={[-1.19, -1.55, 1.94]} />
        <mesh name="Neon84" geometry={nodes.Neon84.geometry} material={materials.Neon_text4} position={[30.8, -7.49, -1888.49]} rotation={[-1.55, -0.01, -0.01]} />
        <mesh name="Neon85" geometry={nodes.Neon85.geometry} material={materials.Neon_text4} position={[30.8, -7.49, -2039.29]} rotation={[-1.55, -0.01, -0.01]} />
        <mesh name="Neon86" geometry={nodes.Neon86.geometry} material={materials.Neon_text4} position={[-83.53, 224.35, -2156.02]} rotation={[-3.12, 0, -0.01]} />
        <mesh name="Neon87" geometry={nodes.Neon87.geometry} material={materials.Neon_text4} position={[-129.26, 224.35, -2107.42]} rotation={[-1.57, -1.55, 1.57]} />
        <mesh name="Neon88" geometry={nodes.Neon88.geometry} material={materials.Neon_text4} position={[-174.45, 224.35, -2156.37]} rotation={[-3.12, 0, -0.01]} />
        <mesh name="Neon89" geometry={nodes.Neon89.geometry} material={materials.Neon_text4} position={[-129.26, 224.35, -2199.78]} rotation={[-1.57, -1.55, 1.57]} />
        <mesh name="Lab2_windows_1001" geometry={nodes.Lab2_windows_1001.geometry} material={materials.Fake_windows} position={[-112.83, 39.05, -761.96]} />
        <mesh name="Lab2_windows_1002" geometry={nodes.Lab2_windows_1002.geometry} material={materials.Fake_windows} position={[-505.43, 50.94, -762.96]} rotation={[0, 0.01, 0]} />
        <mesh name="Lab2_windows_1029" geometry={nodes.Lab2_windows_1029.geometry} material={materials.Fake_windows} position={[-112.83, 39.05, -1072.75]} />
        <mesh name="Lab2_windows_1030" geometry={nodes.Lab2_windows_1030.geometry} material={materials.Fake_windows} position={[-505.43, 50.94, -1073.94]} rotation={[0, 0.01, 0]} />
        <mesh name="Lab2_windows_1037" geometry={nodes.Lab2_windows_1037.geometry} material={materials.Fake_windows} position={[-112.83, 118.78, -761.96]} />
        <mesh name="Lab2_windows_1038" geometry={nodes.Lab2_windows_1038.geometry} material={materials.Fake_windows} position={[-505.43, 130.67, -762.96]} rotation={[0, 0.01, 0]} />
        <mesh name="Lab2_windows_1039" geometry={nodes.Lab2_windows_1039.geometry} material={materials.Fake_windows} position={[-112.83, 117.9, -1072.75]} />
        <mesh name="Lab2_windows_1040" geometry={nodes.Lab2_windows_1040.geometry} material={materials.Fake_windows} position={[-505.43, 129.79, -1073.94]} rotation={[0, 0.01, 0]} />
        <mesh name="Lab2_windows_1003" geometry={nodes.Lab2_windows_1003.geometry} material={materials.Fake_windows} position={[-26.89, 6.96, -762.96]} rotation={[0, 0.01, 0]} />
        <mesh name="Cube183" geometry={nodes.Cube183.geometry} material={materials.Neon_text3} position={[-83.53, 56.11, -762.27]} rotation={[1.59, 0, -0.01]} />
        <mesh name="Cube362" geometry={nodes.Cube362.geometry} material={materials.Neon_text3} position={[-83.06, 163.55, -923.64]} rotation={[-3.12, 0, -0.01]} />
        <mesh name="Cube363" geometry={nodes.Cube363.geometry} material={materials.Neon_text3} position={[-83.53, 53.59, -1075.05]} rotation={[1.59, 0, -0.01]} />
        <mesh name="Cube364" geometry={nodes.Cube364.geometry} material={materials.Neon_text3} position={[-83.53, 194.29, -982.48]} rotation={[-1.55, 0, -0.01]} />
        <mesh name="Cube365" geometry={nodes.Cube365.geometry} material={materials.Neon_text3} position={[-174.05, 194.29, -982.48]} rotation={[-1.55, 0, -0.01]} />
        <mesh name="Cube366" geometry={nodes.Cube366.geometry} material={materials.Neon_text3} position={[-174.05, 94.51, -1073.44]} rotation={[-1.55, 0, -0.01]} />
        <mesh name="Cube367" geometry={nodes.Cube367.geometry} material={materials.Neon_text3} position={[-550.67, 61.77, -1073.44]} rotation={[-1.55, 0, -0.01]} />
        <mesh name="Cube368" geometry={nodes.Cube368.geometry} material={materials.Neon_text3} position={[-553.2, 164.68, -924.25]} rotation={[-3.12, 0, -0.01]} />
        <mesh name="Cube369" geometry={nodes.Cube369.geometry} material={materials.Neon_text3} position={[-553.39, 56.11, -762.27]} rotation={[1.59, 0, -0.01]} />
        <mesh name="Cube411" geometry={nodes.Cube411.geometry} material={materials.Neon_text3} position={[-326.18, 168.04, -762.27]} rotation={[-Math.PI, -1.55, 1.57]} />
        <mesh name="Cube412" geometry={nodes.Cube412.geometry} material={materials.Neon_text3} position={[-326.18, 168.04, -1074.78]} rotation={[-Math.PI, -1.55, 1.57]} />
        <mesh name="Cube413" geometry={nodes.Cube413.geometry} material={materials.Neon_text3} position={[-83.53, 60.93, -843.19]} rotation={[-3.12, -0.01, -0.01]} />
        <mesh name="Cube414" geometry={nodes.Cube414.geometry} material={materials.Neon_text3} position={[30.8, 60.93, -843.19]} rotation={[-3.12, -0.01, -0.01]} />
        <mesh name="Cube415" geometry={nodes.Cube415.geometry} material={materials.Neon_text3} position={[-29.9, 60.93, -761.72]} rotation={[-1.19, -1.55, 1.94]} />
        <mesh name="Cube416" geometry={nodes.Cube416.geometry} material={materials.Neon_text3} position={[-29.9, 60.93, -912.23]} rotation={[-1.19, -1.55, 1.94]} />
        <mesh name="Cube417" geometry={nodes.Cube417.geometry} material={materials.Neon_text3} position={[30.8, -7.49, -762.19]} rotation={[-1.55, -0.01, -0.01]} />
        <mesh name="Cube418" geometry={nodes.Cube418.geometry} material={materials.Neon_text3} position={[30.8, -7.49, -912.99]} rotation={[-1.55, -0.01, -0.01]} />
        <mesh name="Cube419" geometry={nodes.Cube419.geometry} material={materials.Neon_text3} position={[-83.53, 224.35, -1029.72]} rotation={[-3.12, 0, -0.01]} />
        <mesh name="Cube420" geometry={nodes.Cube420.geometry} material={materials.Neon_text3} position={[-129.26, 224.35, -981.13]} rotation={[-1.57, -1.55, 1.57]} />
        <mesh name="Cube421" geometry={nodes.Cube421.geometry} material={materials.Neon_text3} position={[-174.45, 224.35, -1030.07]} rotation={[-3.12, 0, -0.01]} />
        <mesh name="Cube422" geometry={nodes.Cube422.geometry} material={materials.Neon_text3} position={[-129.26, 224.35, -1073.48]} rotation={[-1.57, -1.55, 1.57]} />
        <mesh name="Neon32" geometry={nodes.Neon32.geometry} material={materials.Neon_text3} position={[-348.04, 86.45, -217.72]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Neon31" geometry={nodes.Neon31.geometry} material={materials.Neon_text3} position={[-348.04, 57.24, -218.7]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Neon29" geometry={nodes.Neon29.geometry} material={materials.Neon_text3} position={[-348.04, 41.4, -286.67]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Neon38" geometry={nodes.Neon38.geometry} material={materials.Neon_text3} position={[-229.19, 57.24, -80.91]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Neon37" geometry={nodes.Neon37.geometry} material={materials.Neon_text3} position={[-231.35, 86.45, -83.08]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Neon26" geometry={nodes.Neon26.geometry} material={materials.Neon_text3} position={[-25.61, 97.62, -184.34]} rotation={[2.77, 0.04, -3.14]} />
        <mesh name="Neon28" geometry={nodes.Neon28.geometry} material={materials.Neon_text3} position={[-26.68, 47.83, -254.56]} rotation={[2.89, 0.05, -3.13]} />
        <mesh name="Neon24" geometry={nodes.Neon24.geometry} material={materials.Neon_text3} position={[91.26, 97.62, -115.04]} rotation={[0.37, -0.04, 0]} />
        <mesh name="Neon23" geometry={nodes.Neon23.geometry} material={materials.Neon_text3} position={[89.26, 70.79, -82.64]} rotation={[1.66, 0, -0.01]} />
        <mesh name="Neon27" geometry={nodes.Neon27.geometry} material={materials.Neon_text3} position={[-28.37, 70.79, -218.18]} rotation={[1.66, 0, -0.01]} />
        <mesh name="Neon22" geometry={nodes.Neon22.geometry} material={materials.Neon_text3} position={[90.05, 47.51, -50.07]} rotation={[0.24, -0.04, 0]} />
        <mesh name="Neon21" geometry={nodes.Neon21.geometry} material={materials.Neon_text3} position={[89.26, -1.11, -18.38]} rotation={[1.66, 0, -0.01]} />
        <mesh name="Neon25" geometry={nodes.Neon25.geometry} material={materials.Neon_text3} position={[-287.57, 112.3, -146.59]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Neon36" geometry={nodes.Neon36.geometry} material={materials.Neon_text3} position={[-557.4, 70.79, -80.98]} rotation={[1.66, 0, -0.01]} />
        <mesh name="Neon33" geometry={nodes.Neon33.geometry} material={materials.Neon_text3} position={[-668.82, 70.45, -216.9]} rotation={[1.66, 0, -0.01]} />
        <mesh name="Neon34" geometry={nodes.Neon34.geometry} material={materials.Neon_text3} position={[-667.66, 98.47, -181.26]} rotation={[2.77, 0.04, -3.14]} />
        <mesh name="Neon30" geometry={nodes.Neon30.geometry} material={materials.Neon_text3} position={[-667.32, 47.83, -254.56]} rotation={[2.89, 0.05, -3.13]} />
        <mesh name="Neon35" geometry={nodes.Neon35.geometry} material={materials.Neon_text3} position={[-557.71, 98.52, -113.94]} rotation={[-2.79, 0.07, 3.13]} />
        <mesh name="Neon39" geometry={nodes.Neon39.geometry} material={materials.Neon_text3} position={[-557.71, 47.88, -51.05]} rotation={[-2.92, 0.07, 3.13]} />
        <mesh name="Neon40" geometry={nodes.Neon40.geometry} material={materials.Neon_text3} position={[-236.13, 41.4, -19.47]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Neon12" geometry={nodes.Neon12.geometry} material={materials.Neon} position={[-348.04, 86.45, 604.67]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Neon14" geometry={nodes.Neon14.geometry} material={materials.Neon} position={[-348.04, 57.24, 603.69]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Neon15" geometry={nodes.Neon15.geometry} material={materials.Neon} position={[-348.04, 41.4, 535.72]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Neon4" geometry={nodes.Neon4.geometry} material={materials.Neon} position={[-229.19, 57.24, 741.48]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Neon2" geometry={nodes.Neon2.geometry} material={materials.Neon} position={[-231.35, 86.45, 739.31]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Neon18" geometry={nodes.Neon18.geometry} material={materials.Neon} position={[-25.61, 97.62, 638.05]} rotation={[2.77, 0.04, -3.14]} />
        <mesh name="Neon16" geometry={nodes.Neon16.geometry} material={materials.Neon} position={[-26.68, 47.83, 567.83]} rotation={[2.89, 0.05, -3.13]} />
        <mesh name="Neon3" geometry={nodes.Neon3.geometry} material={materials.Neon} position={[91.26, 97.62, 707.35]} rotation={[0.37, -0.04, 0]} />
        <mesh name="Neon1" geometry={nodes.Neon1.geometry} material={materials.Neon} position={[89.26, 70.79, 739.75]} rotation={[1.66, 0, -0.01]} />
        <mesh name="Neon17" geometry={nodes.Neon17.geometry} material={materials.Neon} position={[-28.37, 70.79, 604.21]} rotation={[1.66, 0, -0.01]} />
        <mesh name="Neon5" geometry={nodes.Neon5.geometry} material={materials.Neon} position={[90.05, 47.51, 772.32]} rotation={[0.24, -0.04, 0]} />
        <mesh name="Neon10" geometry={nodes.Neon10.geometry} material={materials.Neon} position={[-287.57, 112.3, 675.8]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Neon8" geometry={nodes.Neon8.geometry} material={materials.Neon} position={[-557.4, 70.79, 741.41]} rotation={[1.66, 0, -0.01]} />
        <mesh name="Neon13" geometry={nodes.Neon13.geometry} material={materials.Neon} position={[-668.82, 70.45, 605.49]} rotation={[1.66, 0, -0.01]} />
        <mesh name="Neon11" geometry={nodes.Neon11.geometry} material={materials.Neon} position={[-667.66, 98.47, 641.13]} rotation={[2.77, 0.04, -3.14]} />
        <mesh name="Neon19" geometry={nodes.Neon19.geometry} material={materials.Neon} position={[-667.32, 47.83, 567.83]} rotation={[2.89, 0.05, -3.13]} />
        <mesh name="Neon9" geometry={nodes.Neon9.geometry} material={materials.Neon} position={[-557.71, 98.52, 708.45]} rotation={[-2.79, 0.07, 3.13]} />
        <mesh name="Neon7" geometry={nodes.Neon7.geometry} material={materials.Neon} position={[-557.71, 47.88, 771.34]} rotation={[-2.92, 0.07, 3.13]} />
        <mesh name="Neon6" geometry={nodes.Neon6.geometry} material={materials.Neon} position={[-236.13, 41.4, 802.92]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Neon20" geometry={nodes.Neon20.geometry} material={materials.Neon} position={[89.26, -1.11, 804.01]} rotation={[1.66, 0, -0.01]} />
        <mesh name="Neon75" geometry={nodes.Neon75.geometry} material={materials.Neon_text6} position={[630.77, 14.13, -2809.16]} rotation={[1.55, 0, 3.14]} />
        <mesh name="Neon76" geometry={nodes.Neon76.geometry} material={materials.Neon_text6} position={[630.3, 121.57, -2647.8]} rotation={[-0.02, 0, 3.14]} />
        <mesh name="Neon77" geometry={nodes.Neon77.geometry} material={materials.Neon_text6} position={[630.77, 11.62, -2496.38]} rotation={[1.55, 0, 3.14]} />
        <mesh name="Neon78" geometry={nodes.Neon78.geometry} material={materials.Neon_text6} position={[630.77, 152.32, -2588.96]} rotation={[-1.59, 0, 3.14]} />
        <mesh name="Neon94" geometry={nodes.Neon94.geometry} material={materials.Neon_text6} position={[721.29, 52.54, -2498]} rotation={[-1.59, 0, 3.14]} />
        <mesh name="Neon95" geometry={nodes.Neon95.geometry} material={materials.Neon_text6} position={[1097.91, 19.79, -2498]} rotation={[-1.59, 0, 3.14]} />
        <mesh name="Neon96" geometry={nodes.Neon96.geometry} material={materials.Neon_text6} position={[1100.44, 122.71, -2647.18]} rotation={[-0.02, 0, 3.14]} />
        <mesh name="Neon113" geometry={nodes.Neon113.geometry} material={materials.Neon_text6} position={[1100.62, 14.13, -2809.16]} rotation={[1.55, 0, 3.14]} />
        <mesh name="Neon114" geometry={nodes.Neon114.geometry} material={materials.Neon_text6} position={[873.42, 126.06, -2809.16]} rotation={[0, 1.55, -1.58]} />
        <mesh name="Neon115" geometry={nodes.Neon115.geometry} material={materials.Neon_text6} position={[873.42, 126.06, -2496.65]} rotation={[0, 1.55, -1.58]} />
        <mesh name="Neon116" geometry={nodes.Neon116.geometry} material={materials.Neon_text6} position={[630.77, 18.95, -2728.24]} rotation={[-0.02, 0.01, 3.14]} />
        <mesh name="Neon117" geometry={nodes.Neon117.geometry} material={materials.Neon_text6} position={[516.44, 18.95, -2728.24]} rotation={[-0.02, 0.01, 3.14]} />
        <mesh name="Neon118" geometry={nodes.Neon118.geometry} material={materials.Neon_text6} position={[577.14, 18.95, -2809.71]} rotation={[-1.95, 1.55, -1.2]} />
        <mesh name="Neon119" geometry={nodes.Neon119.geometry} material={materials.Neon_text6} position={[577.14, 18.95, -2659.21]} rotation={[-1.95, 1.55, -1.2]} />
        <mesh name="Neon120" geometry={nodes.Neon120.geometry} material={materials.Neon_text6} position={[516.44, -49.46, -2809.25]} rotation={[-1.59, 0.01, 3.14]} />
        <mesh name="Neon121" geometry={nodes.Neon121.geometry} material={materials.Neon_text6} position={[516.44, -49.46, -2658.44]} rotation={[-1.59, 0.01, 3.14]} />
        <mesh name="Neon122" geometry={nodes.Neon122.geometry} material={materials.Neon_text6} position={[630.77, 182.37, -2541.71]} rotation={[-0.02, 0, 3.14]} />
        <mesh name="Neon123" geometry={nodes.Neon123.geometry} material={materials.Neon_text6} position={[676.5, 182.37, -2590.31]} rotation={[-1.57, 1.55, -1.58]} />
        <mesh name="Neon124" geometry={nodes.Neon124.geometry} material={materials.Neon_text6} position={[721.69, 182.37, -2541.37]} rotation={[-0.02, 0, 3.14]} />
        <mesh name="Neon125" geometry={nodes.Neon125.geometry} material={materials.Neon_text6} position={[676.5, 182.37, -2497.96]} rotation={[-1.57, 1.55, -1.58]} />
        <mesh name="Neon52" geometry={nodes.Neon52.geometry} material={materials.Neon_text5} position={[630.77, 14.13, -2034.2]} rotation={[1.55, 0, 3.14]} />
        <mesh name="Neon53" geometry={nodes.Neon53.geometry} material={materials.Neon_text5} position={[630.3, 121.57, -1872.83]} rotation={[-0.02, 0, 3.14]} />
        <mesh name="Neon54" geometry={nodes.Neon54.geometry} material={materials.Neon_text5} position={[630.77, 11.62, -1721.42]} rotation={[1.55, 0, 3.14]} />
        <mesh name="Neon55" geometry={nodes.Neon55.geometry} material={materials.Neon_text5} position={[630.77, 152.32, -1813.99]} rotation={[-1.59, 0, 3.14]} />
        <mesh name="Neon56" geometry={nodes.Neon56.geometry} material={materials.Neon_text5} position={[721.29, 152.32, -1813.99]} rotation={[-1.59, 0, 3.14]} />
        <mesh name="Neon59" geometry={nodes.Neon59.geometry} material={materials.Neon_text5} position={[721.29, 52.54, -1723.03]} rotation={[-1.59, 0, 3.14]} />
        <mesh name="Neon60" geometry={nodes.Neon60.geometry} material={materials.Neon_text5} position={[1097.91, 19.79, -1723.03]} rotation={[-1.59, 0, 3.14]} />
        <mesh name="Neon61" geometry={nodes.Neon61.geometry} material={materials.Neon_text5} position={[1100.44, 122.71, -1872.22]} rotation={[-0.02, 0, 3.14]} />
        <mesh name="Neon62" geometry={nodes.Neon62.geometry} material={materials.Neon_text5} position={[1100.62, 14.13, -2034.2]} rotation={[1.55, 0, 3.14]} />
        <mesh name="Neon63" geometry={nodes.Neon63.geometry} material={materials.Neon_text5} position={[873.42, 126.06, -2034.2]} rotation={[0, 1.55, -1.58]} />
        <mesh name="Neon64" geometry={nodes.Neon64.geometry} material={materials.Neon_text5} position={[873.42, 126.06, -1721.69]} rotation={[0, 1.55, -1.58]} />
        <mesh name="Neon65" geometry={nodes.Neon65.geometry} material={materials.Neon_text5} position={[630.77, 18.95, -1953.28]} rotation={[-0.02, 0.01, 3.14]} />
        <mesh name="Neon66" geometry={nodes.Neon66.geometry} material={materials.Neon_text5} position={[516.44, 18.95, -1953.28]} rotation={[-0.02, 0.01, 3.14]} />
        <mesh name="Neon67" geometry={nodes.Neon67.geometry} material={materials.Neon_text5} position={[577.14, 18.95, -2034.75]} rotation={[-1.95, 1.55, -1.2]} />
        <mesh name="Neon68" geometry={nodes.Neon68.geometry} material={materials.Neon_text5} position={[577.14, 18.95, -1884.24]} rotation={[-1.95, 1.55, -1.2]} />
        <mesh name="Neon69" geometry={nodes.Neon69.geometry} material={materials.Neon_text5} position={[516.44, -49.46, -2034.28]} rotation={[-1.59, 0.01, 3.14]} />
        <mesh name="Neon70" geometry={nodes.Neon70.geometry} material={materials['Neon_text3.001']} position={[516.44, -49.46, -1883.48]} rotation={[-1.59, 0.01, 3.14]} />
        <mesh name="Neon71" geometry={nodes.Neon71.geometry} material={materials.Neon_text5} position={[630.77, 182.37, -1766.75]} rotation={[-0.02, 0, 3.14]} />
        <mesh name="Neon72" geometry={nodes.Neon72.geometry} material={materials.Neon_text5} position={[676.5, 182.37, -1815.34]} rotation={[-1.57, 1.55, -1.58]} />
        <mesh name="Neon73" geometry={nodes.Neon73.geometry} material={materials.Neon_text5} position={[721.69, 182.37, -1766.4]} rotation={[-0.02, 0, 3.14]} />
        <mesh name="Neon74" geometry={nodes.Neon74.geometry} material={materials.Neon_text5} position={[676.5, 182.37, -1722.99]} rotation={[-1.57, 1.55, -1.58]} />
        <mesh name="Neon126" geometry={nodes.Neon126.geometry} material={materials.Neon_text6} position={[630.77, 14.13, -1329.8]} rotation={[1.55, 0, 3.14]} />
        <mesh name="Neon127" geometry={nodes.Neon127.geometry} material={materials.Neon_text6} position={[630.3, 121.57, -1168.43]} rotation={[-0.02, 0, 3.14]} />
        <mesh name="Neon128" geometry={nodes.Neon128.geometry} material={materials.Neon_text6} position={[630.77, 11.62, -1017.01]} rotation={[1.55, 0, 3.14]} />
        <mesh name="Neon129" geometry={nodes.Neon129.geometry} material={materials.Neon_text6} position={[630.77, 152.32, -1109.59]} rotation={[-1.59, 0, 3.14]} />
        <mesh name="Neon130" geometry={nodes.Neon130.geometry} material={materials.Neon_text6} position={[721.29, 152.32, -1109.59]} rotation={[-1.59, 0, 3.14]} />
        <mesh name="Neon131" geometry={nodes.Neon131.geometry} material={materials.Neon_text6} position={[721.29, 52.54, -1018.63]} rotation={[-1.59, 0, 3.14]} />
        <mesh name="Neon132" geometry={nodes.Neon132.geometry} material={materials.Neon_text6} position={[1097.91, 19.79, -1018.63]} rotation={[-1.59, 0, 3.14]} />
        <mesh name="Neon133" geometry={nodes.Neon133.geometry} material={materials.Neon_text6} position={[1100.44, 122.71, -1167.81]} rotation={[-0.02, 0, 3.14]} />
        <mesh name="Neon134" geometry={nodes.Neon134.geometry} material={materials.Neon_text6} position={[1100.62, 14.13, -1329.8]} rotation={[1.55, 0, 3.14]} />
        <mesh name="Neon135" geometry={nodes.Neon135.geometry} material={materials.Neon_text6} position={[873.42, 126.06, -1329.8]} rotation={[0, 1.55, -1.58]} />
        <mesh name="Neon136" geometry={nodes.Neon136.geometry} material={materials.Neon_text6} position={[873.42, 126.06, -1017.28]} rotation={[0, 1.55, -1.58]} />
        <mesh name="Neon137" geometry={nodes.Neon137.geometry} material={materials.Neon_text6} position={[630.77, 18.95, -1248.87]} rotation={[-0.02, 0.01, 3.14]} />
        <mesh name="Neon138" geometry={nodes.Neon138.geometry} material={materials.Neon_text6} position={[516.44, 18.95, -1248.87]} rotation={[-0.02, 0.01, 3.14]} />
        <mesh name="Neon139" geometry={nodes.Neon139.geometry} material={materials.Neon_text6} position={[577.14, 18.95, -1330.35]} rotation={[-1.95, 1.55, -1.2]} />
        <mesh name="Neon140" geometry={nodes.Neon140.geometry} material={materials.Neon_text6} position={[577.14, 18.95, -1179.84]} rotation={[-1.95, 1.55, -1.2]} />
        <mesh name="Neon141" geometry={nodes.Neon141.geometry} material={materials.Neon_text6} position={[516.44, -49.46, -1329.88]} rotation={[-1.59, 0.01, 3.14]} />
        <mesh name="Neon142" geometry={nodes.Neon142.geometry} material={materials.Neon_text6} position={[516.44, -49.46, -1179.08]} rotation={[-1.59, 0.01, 3.14]} />
        <mesh name="Neon143" geometry={nodes.Neon143.geometry} material={materials.Neon_text6} position={[630.77, 182.37, -1062.35]} rotation={[-0.02, 0, 3.14]} />
        <mesh name="Neon144" geometry={nodes.Neon144.geometry} material={materials.Neon_text6} position={[676.5, 182.37, -1110.94]} rotation={[-1.57, 1.55, -1.58]} />
        <mesh name="Neon145" geometry={nodes.Neon145.geometry} material={materials.Neon_text6} position={[721.69, 182.37, -1062]} rotation={[-0.02, 0, 3.14]} />
        <mesh name="Neon146" geometry={nodes.Neon146.geometry} material={materials.Neon_text6} position={[676.5, 182.37, -1018.59]} rotation={[-1.57, 1.55, -1.58]} />
        <mesh name="Neon57" geometry={nodes.Neon57.geometry} material={materials.Checkpoint_in_neon} position={[870.93, 28.64, -619.54]} rotation={[0, 1.55, -1.58]} />
        <mesh name="Neon58" geometry={nodes.Neon58.geometry} material={materials.Checkpoint_in_neon} position={[870.93, 30.35, -735.28]} rotation={[0, 1.55, -1.58]} />
        <mesh name="Neon163" geometry={nodes.Neon163.geometry} material={materials.Neon_text2} position={[1179.05, 19.31, -767.99]} rotation={[-0.33, 0.33, 1.49]} />
        <mesh name="Neon185" geometry={nodes.Neon185.geometry} material={materials.Neon} position={[901.12, -25.73, 480.4]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
        <mesh name="Neon186" geometry={nodes.Neon186.geometry} material={materials.Neon} position={[901.82, -25.73, 738.46]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
        <mesh name="Cube280" geometry={nodes.Cube280.geometry} material={materials.Checkpoint_out_neon} position={[1012.14, 37.1, 869.2]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Cube281" geometry={nodes.Cube281.geometry} material={materials.Checkpoint_out_neon} position={[1089.23, 37.1, 791.13]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube282" geometry={nodes.Cube282.geometry} material={materials.Checkpoint_out_neon} position={[1089.23, 37.1, 947.33]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube283" geometry={nodes.Cube283.geometry} material={materials.Checkpoint_out_neon} position={[1167.86, 37.1, 869.82]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Cube274" geometry={nodes.Cube274.geometry} material={materials.Checkpoint_in_neon} position={[616, 37.1, 609.61]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Cube275" geometry={nodes.Cube275.geometry} material={materials.Checkpoint_in_neon} position={[693.09, 37.1, 531.54]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube278" geometry={nodes.Cube278.geometry} material={materials.Checkpoint_in_neon} position={[693.09, 37.1, 687.74]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube279" geometry={nodes.Cube279.geometry} material={materials.Checkpoint_in_neon} position={[771.72, 37.1, 610.23]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Cube541" geometry={nodes.Cube541.geometry} material={materials.Checkpoint_out_neon} position={[563.47, 16.91, -1256.66]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Cube542" geometry={nodes.Cube542.geometry} material={materials.Checkpoint_out_neon} position={[593.76, 16.91, -1287.34]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube543" geometry={nodes.Cube543.geometry} material={materials.Checkpoint_out_neon} position={[593.76, 16.91, -1225.96]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube544" geometry={nodes.Cube544.geometry} material={materials.Checkpoint_out_neon} position={[624.65, 16.91, -1256.42]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Cube527" geometry={nodes.Cube527.geometry} material={materials.Checkpoint_in_neon} position={[773.74, 120.51, -1201.29]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Cube528" geometry={nodes.Cube528.geometry} material={materials.Checkpoint_in_neon} position={[850.83, 120.51, -1279.36]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube529" geometry={nodes.Cube529.geometry} material={materials.Checkpoint_in_neon} position={[850.83, 120.51, -1123.15]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube530" geometry={nodes.Cube530.geometry} material={materials.Checkpoint_in_neon} position={[929.45, 120.51, -1200.66]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Cube471" geometry={nodes.Cube471.geometry} material={materials.Checkpoint_in_neon} position={[773.74, 120.51, -2680.65]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Cube472" geometry={nodes.Cube472.geometry} material={materials.Checkpoint_in_neon} position={[850.83, 120.51, -2758.72]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube473" geometry={nodes.Cube473.geometry} material={materials.Checkpoint_in_neon} position={[850.83, 120.51, -2602.52]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube474" geometry={nodes.Cube474.geometry} material={materials.Checkpoint_in_neon} position={[929.45, 120.51, -2680.03]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Cube475" geometry={nodes.Cube475.geometry} material={materials.Checkpoint_out_neon} position={[563.47, 16.91, -2736.03]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Cube476" geometry={nodes.Cube476.geometry} material={materials.Checkpoint_out_neon} position={[593.76, 16.91, -2766.7]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube539" geometry={nodes.Cube539.geometry} material={materials.Checkpoint_out_neon} position={[593.76, 16.91, -2705.33]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube540" geometry={nodes.Cube540.geometry} material={materials.Checkpoint_out_neon} position={[624.65, 16.91, -2735.79]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Neon79" geometry={nodes.Neon79.geometry} material={materials.Neon_text6} position={[721.29, 152.32, -2588.96]} rotation={[-1.59, 0, 3.14]} />
        <mesh name="Cube477" geometry={nodes.Cube477.geometry} material={materials.Checkpoint_in_neon} position={[773.74, 120.51, -1905.69]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Cube478" geometry={nodes.Cube478.geometry} material={materials.Checkpoint_in_neon} position={[850.83, 120.51, -1983.76]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube479" geometry={nodes.Cube479.geometry} material={materials.Checkpoint_in_neon} position={[850.83, 120.51, -1827.55]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube480" geometry={nodes.Cube480.geometry} material={materials.Checkpoint_in_neon} position={[929.45, 120.51, -1905.07]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Cube484" geometry={nodes.Cube484.geometry} material={materials.Checkpoint_out_neon} position={[563.47, 16.91, -1961.06]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Cube485" geometry={nodes.Cube485.geometry} material={materials.Checkpoint_out_neon} position={[593.76, 16.91, -1991.74]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube486" geometry={nodes.Cube486.geometry} material={materials.Checkpoint_out_neon} position={[593.76, 16.91, -1930.37]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube487" geometry={nodes.Cube487.geometry} material={materials.Checkpoint_out_neon} position={[624.65, 16.91, -1960.82]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Cube356" geometry={nodes.Cube356.geometry} material={materials.Checkpoint_in_neon} position={[-226.5, 162.49, -2017.08]} />
        <mesh name="Cube357" geometry={nodes.Cube357.geometry} material={materials.Checkpoint_in_neon} position={[-303.59, 162.49, -1939.01]} rotation={[0, 1.57, 0]} />
        <mesh name="Cube358" geometry={nodes.Cube358.geometry} material={materials.Checkpoint_in_neon} position={[-303.59, 162.49, -2095.21]} rotation={[0, 1.57, 0]} />
        <mesh name="Cube359" geometry={nodes.Cube359.geometry} material={materials.Checkpoint_in_neon} position={[-382.21, 162.49, -2017.7]} />
        <mesh name="Cube360" geometry={nodes.Cube360.geometry} material={materials.Checkpoint_out_neon} position={[-16.23, 58.89, -1961.7]} />
        <mesh name="Cube361" geometry={nodes.Cube361.geometry} material={materials.Checkpoint_out_neon} position={[-46.52, 58.89, -1931.03]} rotation={[0, 1.57, 0]} />
        <mesh name="Cube370" geometry={nodes.Cube370.geometry} material={materials.Checkpoint_out_neon} position={[-46.52, 58.89, -1992.4]} rotation={[0, 1.57, 0]} />
        <mesh name="Cube371" geometry={nodes.Cube371.geometry} material={materials.Checkpoint_out_neon} position={[-77.41, 58.89, -1961.95]} />
        <mesh name="Cube452" geometry={nodes.Cube452.geometry} material={materials.Checkpoint_in_neon} position={[-226.5, 162.49, -2787.57]} />
        <mesh name="Cube453" geometry={nodes.Cube453.geometry} material={materials.Checkpoint_in_neon} position={[-303.59, 162.49, -2709.5]} rotation={[0, 1.57, 0]} />
        <mesh name="Cube454" geometry={nodes.Cube454.geometry} material={materials.Checkpoint_in_neon} position={[-303.59, 162.49, -2865.71]} rotation={[0, 1.57, 0]} />
        <mesh name="Cube455" geometry={nodes.Cube455.geometry} material={materials.Checkpoint_in_neon} position={[-382.21, 162.49, -2788.19]} />
        <mesh name="Cube532" geometry={nodes.Cube532.geometry} material={materials.Checkpoint_out_neon} position={[-16.23, 58.89, -2732.2]} />
        <mesh name="Cube533" geometry={nodes.Cube533.geometry} material={materials.Checkpoint_out_neon} position={[-46.52, 58.89, -2701.52]} rotation={[0, 1.57, 0]} />
        <mesh name="Cube534" geometry={nodes.Cube534.geometry} material={materials.Checkpoint_out_neon} position={[-46.52, 58.89, -2762.89]} rotation={[0, 1.57, 0]} />
        <mesh name="Cube538" geometry={nodes.Cube538.geometry} material={materials.Checkpoint_out_neon} position={[-77.41, 58.89, -2732.44]} />
        <mesh name="Neon44" geometry={nodes.Neon44.geometry} material={materials.Neon_text4} position={[-83.53, 194.29, -2108.78]} rotation={[-1.55, 0, -0.01]} />
        <mesh name="Cube423" geometry={nodes.Cube423.geometry} material={materials.Checkpoint_in_neon} position={[-226.5, 162.49, -890.78]} />
        <mesh name="Cube424" geometry={nodes.Cube424.geometry} material={materials.Checkpoint_in_neon} position={[-303.59, 162.49, -812.71]} rotation={[0, 1.57, 0]} />
        <mesh name="Cube425" geometry={nodes.Cube425.geometry} material={materials.Checkpoint_in_neon} position={[-303.59, 162.49, -968.92]} rotation={[0, 1.57, 0]} />
        <mesh name="Cube426" geometry={nodes.Cube426.geometry} material={materials.Checkpoint_in_neon} position={[-382.21, 162.49, -891.4]} />
        <mesh name="Cube427" geometry={nodes.Cube427.geometry} material={materials.Checkpoint_out_neon} position={[-16.23, 58.89, -835.41]} />
        <mesh name="Cube428" geometry={nodes.Cube428.geometry} material={materials.Checkpoint_out_neon} position={[-46.52, 58.89, -804.73]} rotation={[0, 1.57, 0]} />
        <mesh name="Cube429" geometry={nodes.Cube429.geometry} material={materials.Checkpoint_out_neon} position={[-46.52, 58.89, -866.11]} rotation={[0, 1.57, 0]} />
        <mesh name="Cube430" geometry={nodes.Cube430.geometry} material={materials.Checkpoint_out_neon} position={[-77.41, 58.89, -835.65]} />
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials.Building_material} position={[-1251.2, 354.15, 533.22]} scale={[20.71, 115.72, 4.88]} />
        <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials.Building_material} position={[-1283.16, 449.68, 533.2]} rotation={[0, 0, -Math.PI / 2]} scale={[4.15, 12, 4.15]} />
        <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials.Building_material} position={[-1283.16, 257.7, 533.2]} rotation={[0, 0, -Math.PI / 2]} scale={[4.15, 12, 4.15]} />
      </group>
    </group>
  )
}

useGLTF.preload('/EmitBodies-transformed.glb')
