/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 EntranceSign.glb -T
*/

import { useAnimations, useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'

export function EntranceSign(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/EntranceSign-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group scale={0.1} ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Cube056" geometry={nodes.Cube056.geometry} material={materials['Entrance Sign_5']} position={[229.48, 134.87, 1102.9]} rotation={[0, 0.35, 0]} />
        <group name="Cube467" position={[222.45, 95.02, 1096.29]} rotation={[0, 0.35, 0]}>
          <mesh name="Cube362" geometry={nodes.Cube362.geometry} material={materials['Entrance Sign_1']} />
          <mesh name="Cube362_1" geometry={nodes.Cube362_1.geometry} material={materials['Entrance Sign_5.001']} />
        </group>
        <mesh name="Cube468" geometry={nodes.Cube468.geometry} material={materials['Entrance Sign_2']} position={[145.51, 95.02, 1114.44]} rotation={[0, 0.35, 0]} />
        <mesh name="Cube469" geometry={nodes.Cube469.geometry} material={materials['Entrance Sign_2']} position={[200.53, 95.02, 1094.49]} rotation={[0, 0.35, 0]} />
        <mesh name="Cube470" geometry={nodes.Cube470.geometry} material={materials['Entrance Sign_2']} position={[173.89, 223.8, 1104.15]} rotation={[0, 0.35, -Math.PI / 2]} />
        <mesh name="Cube057" geometry={nodes.Cube057.geometry} material={materials.Neon_bars} position={[230.1, 148.57, 1107.14]} rotation={[0, 0.35, 0]} />
        <mesh name="Cube058" geometry={nodes.Cube058.geometry} material={materials.Neon_bars} position={[230.1, 121.93, 1107.14]} rotation={[0, 0.35, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/EntranceSign-transformed.glb')
