/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Floors.glb -T
*/

import { useAnimations, useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'

export function Floors(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Floors-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group scale={0.1} ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="CRC_Hill" geometry={nodes.CRC_Hill.geometry} material={materials.Concrete} position={[-1199.53, 87.8, 233.33]} />
        <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials.Concrete} position={[346.95, -43.05, 571.77]} />
        <mesh name="Cube545" geometry={nodes.Cube545.geometry} material={materials.Concrete} position={[-231.57, -140.2, -1063.12]} />
        <mesh name="Cube607" geometry={nodes.Cube607.geometry} material={materials.Concrete} position={[71.74, -111.46, -1183.08]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Floors-transformed.glb')
