/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Grass.glb --transform
*/

import { useAnimations, useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'

export function Grass(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Grass-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group scale={0.1} ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials.Grass} position={[-237.18, -39.04, 428.45]} />
        <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials.Grass} position={[-237.18, -39.04, 106.83]} />
        <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials.Grass} position={[-237.18, -39.04, -379.54]} />
        <mesh name="Plane004" geometry={nodes.Plane004.geometry} material={materials.Grass} position={[-237.18, -39.04, -686.23]} />
        <mesh name="Plane005" geometry={nodes.Plane005.geometry} material={materials.Grass} position={[-237.18, -39.04, -1488.89]} />
        <mesh name="Plane006" geometry={nodes.Plane006.geometry} material={materials.Grass} position={[-237.18, -39.04, -2279.74]} />
        <mesh name="Plane007" geometry={nodes.Plane007.geometry} material={materials.Grass} position={[-245.95, -39.04, -2555.35]} />
        <mesh name="Plane008" geometry={nodes.Plane008.geometry} material={materials.Grass} position={[928.39, -80.02, 106.83]} />
        <mesh name="Plane009" geometry={nodes.Plane009.geometry} material={materials.Grass} position={[261.88, -80.06, -1393.99]} rotation={[0, 1.57, 0]} />
        <mesh name="Plane010" geometry={nodes.Plane010.geometry} material={materials.Grass} position={[278.03, -80.06, -2289.82]} rotation={[0, 1.57, 0]} />
        <mesh name="Plane011" geometry={nodes.Plane011.geometry} material={materials.Grass} position={[830.83, -80.29, -2119.64]} />
        <mesh name="Plane013" geometry={nodes.Plane013.geometry} material={materials.Grass} position={[836.17, -79.1, -2435.34]} />
        <mesh name="Plane014" geometry={nodes.Plane014.geometry} material={materials.Grass} position={[812.99, -80.29, -1398.67]} />
        <mesh name="Plane015" geometry={nodes.Plane015.geometry} material={materials.Grass} position={[815.23, -79.1, -1666.67]} />
        <mesh name="Plane016" geometry={nodes.Plane016.geometry} material={materials.Grass} position={[-438.23, -79.66, 1015.57]} />
        <mesh name="Plane017" geometry={nodes.Plane017.geometry} material={materials.Grass} position={[859.94, -78.38, 1158.69]} />
        <mesh name="Plane012" geometry={nodes.Plane012.geometry} material={materials.Grass} position={[-1104.73, 26.44, 236.79]} rotation={[Math.PI / 2, 0.85, -Math.PI / 2]} />
        <mesh name="Plane018" geometry={nodes.Plane018.geometry} material={materials.Grass} position={[-1112.67, 39.14, -633.9]} rotation={[Math.PI / 2, 0.91, -Math.PI / 2]} />
        <mesh name="Plane019" geometry={nodes.Plane019.geometry} material={materials.Grass} position={[-1129.19, 92.72, -920.92]} rotation={[Math.PI / 2, 0.85, -Math.PI / 2]} />
        <mesh name="Plane020" geometry={nodes.Plane020.geometry} material={materials.Grass} position={[-1129.19, 92.72, -1221.59]} rotation={[Math.PI / 2, 0.85, -Math.PI / 2]} />
        <mesh name="Plane021" geometry={nodes.Plane021.geometry} material={materials.Grass} position={[-1572.11, 32.78, 952.47]} rotation={[0.82, -0.01, 0.01]} />
        <mesh name="Plane022" geometry={nodes.Plane022.geometry} material={materials.Grass} position={[-1717.55, 21.89, -798.88]} rotation={[2.45, 0.01, -3.13]} />
        <mesh name="Plane023" geometry={nodes.Plane023.geometry} material={materials.Grass} position={[-1662.81, 141.37, -145.72]} rotation={[0, 1.57, 0]} />
        <mesh name="Cylinder003" geometry={nodes.Cylinder003.geometry} material={materials['Lawn Grass']} position={[368.73, -164.8, -4466.72]} />
        <mesh name="Plane057" geometry={nodes.Plane057.geometry} material={materials.Grass} position={[-1662.81, -79.64, 1564.03]} rotation={[0, 1.57, 0]} />
        <mesh name="Plane058" geometry={nodes.Plane058.geometry} material={materials.Grass} position={[-1662.81, -79.12, -2559.1]} rotation={[0, 1.57, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Grass-transformed.glb')
