/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Ground_Spotlights.glb -T
*/

import { useAnimations, useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'

export function Ground_Spotlights(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Ground_Spotlights-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group scale={0.1} ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Cylinder048" geometry={nodes.Cylinder048.geometry} material={materials['Lamp post']} position={[-737.97, 434.49, -5089.73]} />
        <mesh name="Cylinder049" geometry={nodes.Cylinder049.geometry} material={materials['Lamp post']} position={[-737.97, 995.17, -5089.73]} rotation={[Math.PI / 2, 0, 0.54]} />
        <mesh name="Cylinder050" geometry={nodes.Cylinder050.geometry} material={materials['Lamp post']} position={[-591.29, 1296.86, -5004.18]} rotation={[Math.PI / 2, 0, 0.54]} />
        <mesh name="Cylinder051" geometry={nodes.Cylinder051.geometry} material={materials['Lamp post']} position={[-505.5, 1147.77, -5306.35]} rotation={[0.62, 0.57, -0.49]} />
        <mesh name="Cylinder052" geometry={nodes.Cylinder052.geometry} material={materials['Lamp post']} position={[-824.01, 1147.77, -4789.3]} rotation={[0.69, 0.71, -0.62]} />
        <mesh name="Cylinder053" geometry={nodes.Cylinder053.geometry} material={materials['Lamp post']} position={[-617.86, 1233.01, -5023.09]} rotation={[Math.PI / 2, 0, 0.56]} />
        <mesh name="Cylinder054" geometry={nodes.Cylinder054.geometry} material={materials['Lamp post']} position={[-695.6, 1080.02, -5067.36]} rotation={[1.61, 0, 0.61]} />
        <group name="Cylinder047" position={[-734.11, 1230.36, -4822.1]} rotation={[2.35, -0.08, -0.82]}>
          <mesh name="Cylinder007" geometry={nodes.Cylinder007.geometry} material={materials.Spotlight_material} />
          <mesh name="Cylinder007_1" geometry={nodes.Cylinder007_1.geometry} material={materials.Spotlight_Ground_white} />
        </group>
        <group name="Cylinder055" position={[-658.65, 1230.36, -4949.99]} rotation={[2.35, -0.08, -0.82]}>
          <mesh name="Cylinder015" geometry={nodes.Cylinder015.geometry} material={materials.Spotlight_material} />
          <mesh name="Cylinder015_1" geometry={nodes.Cylinder015_1.geometry} material={materials.Spotlight_Ground_white} />
        </group>
        <group name="Cylinder056" position={[-588.32, 1230.36, -5070.2]} rotation={[2.35, -0.08, -0.82]}>
          <mesh name="Cylinder016" geometry={nodes.Cylinder016.geometry} material={materials.Spotlight_material} />
          <mesh name="Cylinder016_1" geometry={nodes.Cylinder016_1.geometry} material={materials.Spotlight_Ground_white} />
        </group>
        <group name="Cylinder057" position={[-517.98, 1230.36, -5187.86]} rotation={[2.35, -0.08, -0.82]}>
          <mesh name="Cylinder017" geometry={nodes.Cylinder017.geometry} material={materials.Spotlight_material} />
          <mesh name="Cylinder017_1" geometry={nodes.Cylinder017_1.geometry} material={materials.Spotlight_Ground_white} />
        </group>
        <group name="Cylinder058" position={[-804.82, 1078.83, -4879.83]} rotation={[2.35, -0.08, -0.82]}>
          <mesh name="Cylinder018" geometry={nodes.Cylinder018.geometry} material={materials.Spotlight_material} />
          <mesh name="Cylinder018_1" geometry={nodes.Cylinder018_1.geometry} material={materials.Spotlight_Ground_white} />
        </group>
        <group name="Cylinder059" position={[-729.37, 1078.83, -5007.71]} rotation={[2.35, -0.08, -0.82]}>
          <mesh name="Cylinder019" geometry={nodes.Cylinder019.geometry} material={materials.Spotlight_material} />
          <mesh name="Cylinder019_1" geometry={nodes.Cylinder019_1.geometry} material={materials.Spotlight_Ground_white} />
        </group>
        <group name="Cylinder060" position={[-659.03, 1078.83, -5127.93]} rotation={[2.35, -0.08, -0.82]}>
          <mesh name="Cylinder020" geometry={nodes.Cylinder020.geometry} material={materials.Spotlight_material} />
          <mesh name="Cylinder020_1" geometry={nodes.Cylinder020_1.geometry} material={materials.Spotlight_Ground_white} />
        </group>
        <group name="Cylinder061" position={[-588.69, 1078.83, -5245.58]} rotation={[2.35, -0.08, -0.82]}>
          <mesh name="Cylinder021" geometry={nodes.Cylinder021.geometry} material={materials.Spotlight_material} />
          <mesh name="Cylinder021_1" geometry={nodes.Cylinder021_1.geometry} material={materials.Spotlight_Ground_white} />
        </group>
        <mesh name="Cylinder075" geometry={nodes.Cylinder075.geometry} material={materials['Lamp post']} position={[1442.33, 434.49, -5094.95]} rotation={[Math.PI, -1.21, Math.PI]} />
        <mesh name="Cylinder076" geometry={nodes.Cylinder076.geometry} material={materials['Lamp post']} position={[1442.33, 995.17, -5094.95]} rotation={[Math.PI / 2, 0, 2.48]} />
        <mesh name="Cylinder077" geometry={nodes.Cylinder077.geometry} material={materials['Lamp post']} position={[1310.12, 1296.86, -4988.4]} rotation={[Math.PI / 2, 0, 2.48]} />
        <mesh name="Cylinder078" geometry={nodes.Cylinder078.geometry} material={materials['Lamp post']} position={[1561.86, 1147.77, -4800.55]} rotation={[1.09, -0.99, 0.88]} />
        <mesh name="Cylinder079" geometry={nodes.Cylinder079.geometry} material={materials['Lamp post']} position={[1192.3, 1147.77, -5282.44]} rotation={[0.89, -0.89, 0.64]} />
        <mesh name="Cylinder080" geometry={nodes.Cylinder080.geometry} material={materials['Lamp post']} position={[1337.26, 1233.01, -5006.48]} rotation={[Math.PI / 2, 0, 2.5]} />
        <mesh name="Cylinder081" geometry={nodes.Cylinder081.geometry} material={materials['Lamp post']} position={[1406.33, 1080.02, -5063.34]} rotation={[1.56, 0.03, 2.55]} />
        <group name="Cylinder082" position={[1190.91, 1230.36, -5186.74]} rotation={[1.33, 0.75, 1.17]}>
          <mesh name="Cylinder042" geometry={nodes.Cylinder042.geometry} material={materials.Spotlight_material} />
          <mesh name="Cylinder042_1" geometry={nodes.Cylinder042_1.geometry} material={materials.Spotlight_Ground_white} />
        </group>
        <group name="Cylinder083" position={[1283.5, 1230.36, -5070.66]} rotation={[1.33, 0.75, 1.17]}>
          <mesh name="Cylinder043" geometry={nodes.Cylinder043.geometry} material={materials.Spotlight_material} />
          <mesh name="Cylinder043_1" geometry={nodes.Cylinder043_1.geometry} material={materials.Spotlight_Ground_white} />
        </group>
        <group name="Cylinder084" position={[1370.74, 1230.36, -4962.09]} rotation={[1.33, 0.75, 1.17]}>
          <mesh name="Cylinder044" geometry={nodes.Cylinder044.geometry} material={materials.Spotlight_material} />
          <mesh name="Cylinder044_1" geometry={nodes.Cylinder044_1.geometry} material={materials.Spotlight_Ground_white} />
        </group>
        <group name="Cylinder085" position={[1455.6, 1230.36, -4854.44]} rotation={[1.33, 0.75, 1.17]}>
          <mesh name="Cylinder045" geometry={nodes.Cylinder045.geometry} material={materials.Spotlight_material} />
          <mesh name="Cylinder045_1" geometry={nodes.Cylinder045_1.geometry} material={materials.Spotlight_Ground_white} />
        </group>
        <group name="Cylinder086" position={[1270.05, 1078.83, -5232.23]} rotation={[1.33, 0.75, 1.17]}>
          <mesh name="Cylinder046" geometry={nodes.Cylinder046.geometry} material={materials.Spotlight_material} />
          <mesh name="Cylinder046_1" geometry={nodes.Cylinder046_1.geometry} material={materials.Spotlight_Ground_white} />
        </group>
        <group name="Cylinder087" position={[1362.64, 1078.83, -5116.15]} rotation={[1.33, 0.75, 1.17]}>
          <mesh name="Cylinder047_1" geometry={nodes.Cylinder047_1.geometry} material={materials.Spotlight_material} />
          <mesh name="Cylinder047_2" geometry={nodes.Cylinder047_2.geometry} material={materials.Spotlight_Ground_white} />
        </group>
        <group name="Cylinder088" position={[1449.88, 1078.83, -5007.59]} rotation={[1.33, 0.75, 1.17]}>
          <mesh name="Cylinder048_1" geometry={nodes.Cylinder048_1.geometry} material={materials.Spotlight_material} />
          <mesh name="Cylinder048_2" geometry={nodes.Cylinder048_2.geometry} material={materials.Spotlight_Ground_white} />
        </group>
        <group name="Cylinder089" position={[1534.74, 1078.83, -4899.93]} rotation={[1.33, 0.75, 1.17]}>
          <mesh name="Cylinder049_1" geometry={nodes.Cylinder049_1.geometry} material={materials.Spotlight_material} />
          <mesh name="Cylinder049_2" geometry={nodes.Cylinder049_2.geometry} material={materials.Spotlight_Ground_white} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Ground_Spotlights-transformed.glb')
