/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 Hostel23.glb -T
*/

import { useAnimations, useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'

export function Hostel23(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Hostel23-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group scale={0.1} ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Cube384" geometry={nodes.Cube384.geometry} material={materials['Building_material.002']} position={[-26.66, -38.09, -2889.67]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Hostel23-transformed.glb')
