/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 Hostel1.glb -T
*/

import { useAnimations, useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'

export function Hostel1(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Hostel1-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group scale={0.1} ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Cube121" geometry={nodes.Cube121.geometry} material={materials.Building_material} position={[-26.66, -38.09, -992.88]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Hostel1-transformed.glb')
