/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 Lab1.glb -T
*/

import { useAnimations, useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'

export function Lab1(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Lab1-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group scale={0.1} ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Cube019" geometry={nodes.Cube019.geometry} material={materials.Building_material} position={[32.17, -27.0, 539.21]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Lab1-transformed.glb')
