/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 Lab2.glb -T
*/

import { useAnimations, useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'

export function Lab2(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Lab2-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group scale={0.1} ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Cube011" geometry={nodes.Cube011.geometry} material={materials.Building_material} position={[32.17, -27.28, -283.19]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Lab2-transformed.glb')
