/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 LabWindows.glb -T
*/

import { useAnimations, useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'

export function LabWindows(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/LabWindows-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group scale={0.1} ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Lab1_windows_1" geometry={nodes.Lab1_windows_1.geometry} material={materials.Glass} position={[-232.25, 70.46, 738.05]} />
        <mesh name="Lab1_windows_2" geometry={nodes.Lab1_windows_2.geometry} material={materials.Glass} position={[-347.83, 71.81, 606.16]} />
        <mesh name="Lab2_windows_1" geometry={nodes.Lab2_windows_1.geometry} material={materials.Glass} position={[-232.25, 70.46, -84.34]} />
        <mesh name="Lab2_windows_2" geometry={nodes.Lab2_windows_2.geometry} material={materials.Glass} position={[-347.83, 71.81, -216.23]} />
      </group>
    </group>
  )
}

useGLTF.preload('/LabWindows-transformed.glb')
