/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 LampPosts.glb -T
*/

import { useAnimations, useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'

export function LampPosts(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/LampPosts-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group scale={0.1} ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Cylinder004" geometry={nodes.Cylinder004.geometry} material={materials['Lamp post.001']} position={[323.82, -34.29, 678.54]} />
        <mesh name="Cylinder005" geometry={nodes.Cylinder005.geometry} material={materials['Lamp post.001']} position={[323.82, -8.78, 678.54]} />
        <mesh name="Plane024" geometry={nodes.Plane024.geometry} material={materials['Lamp post.001']} position={[323.82, 36.64, 678.54]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Plane025" geometry={nodes.Plane025.geometry} material={materials['Lamp post.001']} position={[323.82, 36.64, 678.54]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh name="Cylinder006" geometry={nodes.Cylinder006.geometry} material={materials['Lamp post.001']} position={[323.82, -34.29, 239.12]} />
        <mesh name="Cylinder007" geometry={nodes.Cylinder007.geometry} material={materials['Lamp post.001']} position={[323.82, -8.78, 239.12]} />
        <mesh name="Plane026" geometry={nodes.Plane026.geometry} material={materials['Lamp post.001']} position={[323.82, 36.64, 239.12]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Plane027" geometry={nodes.Plane027.geometry} material={materials['Lamp post.001']} position={[323.82, 36.64, 239.12]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh name="Cylinder008" geometry={nodes.Cylinder008.geometry} material={materials['Lamp post.001']} position={[562.09, -74.22, 61.97]} />
        <mesh name="Cylinder009" geometry={nodes.Cylinder009.geometry} material={materials['Lamp post.001']} position={[562.09, -48.7, 61.97]} />
        <mesh name="Plane028" geometry={nodes.Plane028.geometry} material={materials['Lamp post.001']} position={[562.09, -3.28, 61.97]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Plane029" geometry={nodes.Plane029.geometry} material={materials['Lamp post.001']} position={[562.09, -3.28, 61.97]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh name="Cylinder010" geometry={nodes.Cylinder010.geometry} material={materials['Lamp post.001']} position={[255.56, -31.34, -512.78]} />
        <mesh name="Cylinder011" geometry={nodes.Cylinder011.geometry} material={materials['Lamp post.001']} position={[255.56, -5.82, -512.78]} />
        <mesh name="Plane030" geometry={nodes.Plane030.geometry} material={materials['Lamp post.001']} position={[255.56, 39.6, -512.78]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Plane031" geometry={nodes.Plane031.geometry} material={materials['Lamp post.001']} position={[255.56, 39.6, -512.78]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh name="Cylinder012" geometry={nodes.Cylinder012.geometry} material={materials['Lamp post.001']} position={[113.1, -31.34, -1280.65]} />
        <mesh name="Cylinder013" geometry={nodes.Cylinder013.geometry} material={materials['Lamp post.001']} position={[113.1, -5.82, -1280.65]} />
        <mesh name="Plane032" geometry={nodes.Plane032.geometry} material={materials['Lamp post.001']} position={[113.1, 39.6, -1280.65]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Plane033" geometry={nodes.Plane033.geometry} material={materials['Lamp post.001']} position={[113.1, 39.6, -1280.65]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh name="Cylinder014" geometry={nodes.Cylinder014.geometry} material={materials['Lamp post.001']} position={[113.1, -31.34, -1685.1]} />
        <mesh name="Cylinder015" geometry={nodes.Cylinder015.geometry} material={materials['Lamp post.001']} position={[113.1, -5.82, -1685.1]} />
        <mesh name="Plane034" geometry={nodes.Plane034.geometry} material={materials['Lamp post.001']} position={[113.1, 39.6, -1685.1]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Plane035" geometry={nodes.Plane035.geometry} material={materials['Lamp post.001']} position={[113.1, 39.6, -1685.1]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh name="Cylinder016" geometry={nodes.Cylinder016.geometry} material={materials['Lamp post.001']} position={[113.1, -31.34, -2334.41]} />
        <mesh name="Cylinder017" geometry={nodes.Cylinder017.geometry} material={materials['Lamp post.001']} position={[113.1, -5.82, -2334.41]} />
        <mesh name="Plane036" geometry={nodes.Plane036.geometry} material={materials['Lamp post.001']} position={[113.1, 39.6, -2334.41]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Plane037" geometry={nodes.Plane037.geometry} material={materials['Lamp post.001']} position={[113.1, 39.6, -2334.41]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh name="Cylinder018" geometry={nodes.Cylinder018.geometry} material={materials['Lamp post.001']} position={[483.29, -77.16, -2405.57]} />
        <mesh name="Cylinder019" geometry={nodes.Cylinder019.geometry} material={materials['Lamp post.001']} position={[483.29, -51.64, -2405.57]} />
        <mesh name="Plane038" geometry={nodes.Plane038.geometry} material={materials['Lamp post.001']} position={[483.29, -6.23, -2405.57]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Plane039" geometry={nodes.Plane039.geometry} material={materials['Lamp post.001']} position={[483.29, -6.23, -2405.57]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh name="Cylinder020" geometry={nodes.Cylinder020.geometry} material={materials['Lamp post.001']} position={[483.29, -77.16, -1648.2]} />
        <mesh name="Cylinder021" geometry={nodes.Cylinder021.geometry} material={materials['Lamp post.001']} position={[483.29, -51.64, -1648.2]} />
        <mesh name="Plane040" geometry={nodes.Plane040.geometry} material={materials['Lamp post.001']} position={[483.29, -6.23, -1648.2]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Plane041" geometry={nodes.Plane041.geometry} material={materials['Lamp post.001']} position={[483.29, -6.23, -1648.2]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh name="Cylinder022" geometry={nodes.Cylinder022.geometry} material={materials['Lamp post.001']} position={[483.29, -77.16, -1014.44]} />
        <mesh name="Cylinder023" geometry={nodes.Cylinder023.geometry} material={materials['Lamp post.001']} position={[483.29, -51.64, -1014.44]} />
        <mesh name="Plane042" geometry={nodes.Plane042.geometry} material={materials['Lamp post.001']} position={[483.29, -6.23, -1014.44]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Plane043" geometry={nodes.Plane043.geometry} material={materials['Lamp post.001']} position={[483.29, -6.23, -1014.44]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh name="Cylinder024" geometry={nodes.Cylinder024.geometry} material={materials['Lamp post.001']} position={[951.29, -74.22, -386.02]} />
        <mesh name="Cylinder025" geometry={nodes.Cylinder025.geometry} material={materials['Lamp post.001']} position={[951.29, -48.7, -386.02]} />
        <mesh name="Plane044" geometry={nodes.Plane044.geometry} material={materials['Lamp post.001']} position={[951.29, -3.28, -386.02]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Plane045" geometry={nodes.Plane045.geometry} material={materials['Lamp post.001']} position={[951.29, -3.28, -386.02]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh name="Cylinder026" geometry={nodes.Cylinder026.geometry} material={materials['Lamp post.001']} position={[951.29, -74.22, 424.92]} />
        <mesh name="Cylinder027" geometry={nodes.Cylinder027.geometry} material={materials['Lamp post.001']} position={[951.29, -48.7, 424.92]} />
        <mesh name="Plane046" geometry={nodes.Plane046.geometry} material={materials['Lamp post.001']} position={[951.29, -3.28, 424.92]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Plane047" geometry={nodes.Plane047.geometry} material={materials['Lamp post.001']} position={[951.29, -3.28, 424.92]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh name="Cylinder028" geometry={nodes.Cylinder028.geometry} material={materials['Lamp post.001']} position={[-455.61, -73.62, 1046.28]} />
        <mesh name="Cylinder029" geometry={nodes.Cylinder029.geometry} material={materials['Lamp post.001']} position={[-455.61, -48.11, 1046.28]} />
        <mesh name="Plane048" geometry={nodes.Plane048.geometry} material={materials['Lamp post.001']} position={[-455.61, -2.69, 1046.28]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Plane049" geometry={nodes.Plane049.geometry} material={materials['Lamp post.001']} position={[-455.61, -2.69, 1046.28]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh name="Cylinder030" geometry={nodes.Cylinder030.geometry} material={materials['Lamp post.001']} position={[851.26, -73.62, 1154.56]} />
        <mesh name="Cylinder031" geometry={nodes.Cylinder031.geometry} material={materials['Lamp post.001']} position={[851.26, -48.11, 1154.56]} />
        <mesh name="Plane050" geometry={nodes.Plane050.geometry} material={materials['Lamp post.001']} position={[851.26, -2.69, 1154.56]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Plane051" geometry={nodes.Plane051.geometry} material={materials['Lamp post.001']} position={[851.26, -2.69, 1154.56]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh name="Cylinder032" geometry={nodes.Cylinder032.geometry} material={materials['Lamp post.001']} position={[-1505.49, 142.87, 241.49]} />
        <mesh name="Cylinder033" geometry={nodes.Cylinder033.geometry} material={materials['Lamp post.001']} position={[-1505.49, 168.39, 241.49]} />
        <mesh name="Plane052" geometry={nodes.Plane052.geometry} material={materials['Lamp post.001']} position={[-1505.49, 213.81, 241.49]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Plane053" geometry={nodes.Plane053.geometry} material={materials['Lamp post.001']} position={[-1505.49, 213.81, 241.49]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh name="Cylinder034" geometry={nodes.Cylinder034.geometry} material={materials['Lamp post.001']} position={[-1505.49, 142.87, -370.24]} />
        <mesh name="Cylinder035" geometry={nodes.Cylinder035.geometry} material={materials['Lamp post.001']} position={[-1505.49, 168.39, -370.24]} />
        <mesh name="Plane054" geometry={nodes.Plane054.geometry} material={materials['Lamp post.001']} position={[-1505.49, 213.81, -370.24]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Plane055" geometry={nodes.Plane055.geometry} material={materials['Lamp post.001']} position={[-1505.49, 213.81, -370.24]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      </group>
    </group>
  )
}

useGLTF.preload('/LampPosts-transformed.glb')
