/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 Library.glb -T
*/

import { useAnimations, useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'

export function Library(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Library-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group scale={0.1} ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Cube549" geometry={nodes.Cube549.geometry} material={materials.Building_material} position={[1090.44, -82.59, 608.92]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Library-transformed.glb')
