/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Pavements.glb -T
*/

import { useAnimations, useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'

export function Pavements(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Pavements-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group scale={0.1} ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Cube547" geometry={nodes.Cube547.geometry} material={materials.Pavement} position={[-264.32, -44.87, -1765.34]} />
        <mesh name="Cube548" geometry={nodes.Cube548.geometry} material={materials.Pavement} position={[-264.32, -44.87, -2420.27]} />
        <mesh name="Cube546" geometry={nodes.Cube546.geometry} material={materials.Pavement} position={[-264.32, -44.87, -1203.69]} />
        <mesh name="Cube277" geometry={nodes.Cube277.geometry} material={materials.Pavement} position={[-264.32, -44.87, -535.71]} />
        <mesh name="Cube276" geometry={nodes.Cube276.geometry} material={materials.Pavement} position={[-264.32, -44.87, 263.23]} />
        <mesh name="Cube551" geometry={nodes.Cube551.geometry} material={materials.Pavement} position={[788.75, -86.64, -2285.04]} />
        <mesh name="Cube552" geometry={nodes.Cube552.geometry} material={materials.Pavement} position={[788.75, -87.55, -1542.84]} />
        <mesh name="Cube553" geometry={nodes.Cube553.geometry} material={materials.Pavement} position={[831.1, -87.55, -907.65]} />
        <mesh name="Cube006" geometry={nodes.Cube006.geometry} material={materials.Pavement} position={[429.03, -87.55, 1153.33]} rotation={[0, 1.57, 0]} />
        <mesh name="Cube433" geometry={nodes.Cube433.geometry} material={materials.Pavement} position={[-1351.01, 136.86, -65.75]} rotation={[0, 1.57, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Pavements-transformed.glb')
