/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Road_covering_walls.glb -T
*/

import { useAnimations, useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'

export function Road_covering_walls(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Road_covering_walls-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group scale={0.1} ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Cube027" geometry={nodes.Cube027.geometry} material={materials.Concrete_stairs} position={[706.28, -78.12, 1514.67]} />
        <mesh name="Cube026" geometry={nodes.Cube026.geometry} material={materials.Concrete_stairs} position={[1274.28, -72.29, -944.71]} rotation={[0, 1.57, 0]} />
        <mesh name="Cube028" geometry={nodes.Cube028.geometry} material={materials.Concrete_stairs} position={[-317.5, -76.19, 1513.29]} />
        <mesh name="Cube036" geometry={nodes.Cube036.geometry} material={materials.Concrete_stairs} position={[-588.36, -72.46, 1032.3]} rotation={[0, -0.69, 0]} />
        <mesh name="Cube033" geometry={nodes.Cube033.geometry} material={materials.Concrete_stairs} position={[603.09, -68.39, 1270.4]} />
        <mesh name="Cube040" geometry={nodes.Cube040.geometry} material={materials.Concrete_stairs} position={[520.19, -59.12, -3108.75]} rotation={[0, 1.57, 0]} />
        <mesh name="Cube038" geometry={nodes.Cube038.geometry} material={materials.Concrete_stairs} position={[283.03, -59.12, -3101.67]} rotation={[0, 1.57, 0]} />
        <mesh name="Cube042" geometry={nodes.Cube042.geometry} material={materials.Concrete_stairs} position={[-327.21, -72.03, 1114.71]} rotation={[0, 0.58, 0]} />
        <mesh name="Cube055" geometry={nodes.Cube055.geometry} material={materials.Concrete_stairs} position={[-97.11, -71.93, 1213.44]} rotation={[0, 0.47, 0]} />
        <mesh name="Cube025" geometry={nodes.Cube025.geometry} material={materials['Road.001']} position={[413.98, -74.63, 1536.79]} />
        <mesh name="Cube034" geometry={nodes.Cube034.geometry} material={materials.Concrete_stairs} position={[413.98, -74.63, 1281.28]} rotation={[Math.PI, 0, Math.PI]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Road_covering_walls-transformed.glb')
