/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Road.glb -T
*/

import { useAnimations, useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'

export function Road(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Road-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group scale={0.1} ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="BezierCurve001" geometry={nodes.BezierCurve001.geometry} material={materials.Road} position={[234.91, -56.31, -801.53]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Road-transformed.glb')
