/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Spotlights.glb -T
*/

import { useAnimations, useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'

export function SpotLights(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Spotlights-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group scale={0.1} ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Cylinder002" position={[1062.68, 90.49, -53.99]} rotation={[0.53, -0.46, -2.03]} scale={[6.61, 7.48, 6.61]}>
          <mesh name="Cylinder002_1" geometry={nodes.Cylinder002_1.geometry} material={materials.Spotlight_material} >
          <meshNormalMaterial/></mesh>
          <mesh name="Cylinder002_2" geometry={nodes.Cylinder002_2.geometry}> 
          <meshBasicMaterial color={'cyan'}/>
          </mesh>
        </group>
        <group name="Cylinder044" position={[1062.68, 90.49, 180.78]} rotation={[2.49, -0.61, -1.37]} scale={[6.61, 7.48, 6.61]}>
          <mesh name="Cylinder002_1" geometry={nodes.Cylinder002_1.geometry} material={materials.Spotlight_material} >
          <meshNormalMaterial/></mesh>
          <mesh name="Cylinder002_2" geometry={nodes.Cylinder002_2.geometry} material={materials.Spotlight_Red} >
          <meshBasicMaterial color={'orange'}/>
          </mesh>
        </group>

        <group name="Cylinder043" position={[1062.68, 90.49, 60.23]} rotation={[1.11, -0.55, -2.25]} scale={[6.61, 7.48, 6.61]}>
          <mesh name="Cylinder003" geometry={nodes.Cylinder003.geometry} material={materials.Spotlight_material} >
          <meshNormalMaterial/></mesh>
          <mesh name="Cylinder003_1" geometry={nodes.Cylinder003_1.geometry} material={materials.Spotlight_Green} >
          <meshBasicMaterial color={'green'}/>
          </mesh>
        </group>

        <group name="Cylinder045" position={[1062.68, 90.49, 113.19]} rotation={[2.31, -0.28, -1.03]} scale={[6.61, 7.48, 6.61]}>
          <mesh name="Cylinder005" geometry={nodes.Cylinder005.geometry} material={materials.Spotlight_material} >
          <meshNormalMaterial/></mesh>
          <mesh name="Cylinder005_1" geometry={nodes.Cylinder005_1.geometry} material={materials.Spotlight_Blue} > 
          <meshBasicMaterial color={'blue'}/></mesh>
        </group>

        <group name="Cylinder046" position={[1060.19, 90.49, -5.09]} rotation={[1.51, -0.86, -1.12]} scale={[6.61, 7.48, 6.61]}>
          <mesh name="Cylinder005" geometry={nodes.Cylinder005.geometry} material={materials.Spotlight_material} >
          <meshNormalMaterial/></mesh>
          <mesh name="Cylinder005_1" geometry={nodes.Cylinder005_1.geometry} material={materials.Spotlight_Blue} > 
          <meshBasicMaterial color={'red'}/></mesh>
        </group>
        <mesh name="Cube007" geometry={nodes.Cube007.geometry} material={materials.Spotlight_material} position={[1061.25, 96.94, -61.01]} scale={[0.71, 6.62, 0.69]} />
        <mesh name="Cube008" geometry={nodes.Cube008.geometry} material={materials.Spotlight_material} position={[1061.25, 96.94, -47.59]} scale={[0.71, 6.62, 0.69]} />
        <mesh name="Cube013" geometry={nodes.Cube013.geometry} material={materials.Spotlight_material} position={[1061.25, 96.94, -12.84]} scale={[0.71, 6.62, 0.69]} />
        <mesh name="Cube014" geometry={nodes.Cube014.geometry} material={materials.Spotlight_material} position={[1061.25, 96.94, 1.89]} scale={[0.71, 6.62, 0.69]} />
        <mesh name="Cube015" geometry={nodes.Cube015.geometry} material={materials.Spotlight_material} position={[1061.25, 96.94, 54.12]} scale={[0.71, 6.62, 0.69]} />
        <mesh name="Cube016" geometry={nodes.Cube016.geometry} material={materials.Spotlight_material} position={[1061.25, 96.94, 67.89]} scale={[0.71, 6.62, 0.69]} />
        <mesh name="Cube017" geometry={nodes.Cube017.geometry} material={materials.Spotlight_material} position={[1061.25, 96.94, 106.2]} scale={[0.71, 6.62, 0.69]} />
        <mesh name="Cube021" geometry={nodes.Cube021.geometry} material={materials.Spotlight_material} position={[1061.25, 96.94, 119.2]} scale={[0.71, 6.62, 0.69]} />
        <mesh name="Cube022" geometry={nodes.Cube022.geometry} material={materials.Spotlight_material} position={[1061.25, 96.94, 174.2]} scale={[0.71, 6.62, 0.69]} />
        <mesh name="Cube023" geometry={nodes.Cube023.geometry} material={materials.Spotlight_material} position={[1061.25, 96.94, 188.53]} scale={[0.71, 6.62, 0.69]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Spotlights-transformed.glb')
