/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 SteelBars.glb -T
*/

import { useAnimations, useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'

export function SteelBars(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/SteelBars-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group scale={0.1} ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Cube396" geometry={nodes.Cube396.geometry} material={materials['Material.001']} position={[1131.57, 52.47, 58.55]} >
        <meshNormalMaterial/></mesh>
        <mesh name="Cube185" geometry={nodes.Cube185.geometry} material={materials['Material.001']} position={[-233, 19.33, 841.94]} rotation={[Math.PI / 2, 1.57, 0]} >
        <meshNormalMaterial/></mesh>
        <mesh name="Cube024" geometry={nodes.Cube024.geometry} material={materials['Material.001']} position={[41.58, 32.61, 590.33]} rotation={[0, 0, Math.PI]} >
        <meshNormalMaterial/></mesh>
        <mesh name="Cube269" geometry={nodes.Cube269.geometry} material={materials['Material.001']} position={[-231.19, 18.97, 19.81]} >
        <meshNormalMaterial/></mesh>
        <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials['Material.001']} position={[41.58, 32.61, -232.06]} rotation={[0, 0, Math.PI / 2]} >
        <meshNormalMaterial/></mesh>
        <mesh name="Cube122" geometry={nodes.Cube122.geometry} material={materials['Material.001']} position={[-15.21, 50.55, -961.87]} rotation={[0, -1.57, 0]} >
        <meshNormalMaterial/></mesh>
        <mesh name="Cube135" geometry={nodes.Cube135.geometry} material={materials['Material.001']} position={[-15.31, 50.77, -2086.05]} rotation={[0, -1.57, 0]} >
        <meshNormalMaterial/></mesh>
        <mesh name="Cube385" geometry={nodes.Cube385.geometry} material={materials['Material.001']} position={[-15.31, 50.77, -2856.55]} rotation={[0, -1.57, 0]} >
        <meshNormalMaterial/></mesh>
        <mesh name="Cube305" geometry={nodes.Cube305.geometry} material={materials['Material.001']} position={[562.55, 8.79, -2611.68]} rotation={[0, 1.57, 0]} >
        <meshNormalMaterial/></mesh>
        <mesh name="Cube174" geometry={nodes.Cube174.geometry} material={materials['Material.001']} position={[562.55, 8.79, -1836.71]} rotation={[0, 1.57, 0]} >
        <meshNormalMaterial/></mesh>
        <mesh name="Cube032" geometry={nodes.Cube032.geometry} material={materials['Material.001']} position={[883.76, -30.92, -511.67]}>
        <meshNormalMaterial/></mesh>
        <mesh name="Cube612" geometry={nodes.Cube612.geometry} material={materials['Material.001']} position={[1091.88, 12.48, 587.54]} rotation={[0, -1.57, 0]} >
        <meshNormalMaterial/></mesh>
        <mesh name="Cube343" geometry={nodes.Cube343.geometry} material={materials['Material.001']} position={[621.52, 8.79, 900.97]}>
        <meshNormalMaterial/></mesh>
        <mesh name="Cube494" geometry={nodes.Cube494.geometry} material={materials['Material.001']} position={[610.53, 14.15, -1144.43]} rotation={[-Math.PI / 2, 0, -Math.PI]} >
        <meshNormalMaterial/></mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/SteelBars-transformed.glb')
