/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Steps.glb -T
*/

import { useAnimations, useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'

export function Steps(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Steps-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group scale={0.1} ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Cube009" geometry={nodes.Cube009.geometry} material={materials['Concrete_stairs.001']} position={[425.94, -61.34, 878.91]} rotation={[0, 1.57, 0]} />
        <mesh name="Cube284" geometry={nodes.Cube284.geometry} material={materials['Concrete_stairs.001']} position={[424.12, -84.73, 959.99]} rotation={[0, 1.57, 0]} />
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials['Concrete_stairs.001']} position={[238.42, -42.25, -1059.81]} rotation={[0, -1.34, 0]} />
        <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials['Concrete_stairs.001']} position={[1098.35, -75.06, -129.33]} />
        <mesh name="Cube583" geometry={nodes.Cube583.geometry} material={materials['Concrete_stairs.001']} position={[1082.21, -77.06, 269.74]} />
        <mesh name="Cube254" geometry={nodes.Cube254.geometry} material={materials['Concrete_stairs.001']} position={[273.39, -69.95, -228.79]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Cube271" geometry={nodes.Cube271.geometry} material={materials['Concrete_stairs.001']} position={[405.22, -69.95, 82.31]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Cube272" geometry={nodes.Cube272.geometry} material={materials['Concrete_stairs.001']} position={[536.18, -69.4, 281.48]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Cube273" geometry={nodes.Cube273.geometry} material={materials['Concrete_stairs.001']} position={[276.28, -72.65, -1694.49]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Cube554" geometry={nodes.Cube554.geometry} material={materials['Concrete_stairs.001']} position={[435.96, -76.2, -550.97]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Cube409" geometry={nodes.Cube409.geometry} material={materials['Concrete_stairs.001']} position={[-1052.52, 13.95, -425.33]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Cube410" geometry={nodes.Cube410.geometry} material={materials['Concrete_stairs.001']} position={[-1185.79, 86.67, -425.33]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Cube435" geometry={nodes.Cube435.geometry} material={materials['Concrete_stairs.001']} position={[409.71, -72.65, -3406.86]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Cube584" geometry={nodes.Cube584.geometry} material={materials['Concrete_stairs.001']} position={[836.8, -75.06, 757.29]} rotation={[0, 1.57, 0]} />
        <mesh name="Cube408" geometry={nodes.Cube408.geometry} material={materials['Concrete_stairs.001']} position={[-1306.91, 150.74, 432.33]} rotation={[0, 1.57, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Steps-transformed.glb')
