/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Texts2.glb -T
*/

import { useAnimations, useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'

export function Texts(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Texts2-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group scale={0.1} ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Text010" geometry={nodes.Text010.geometry} material={materials.Frontgate_text_neon} position={[421.09, 67.15, 1881.99]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Text011" geometry={nodes.Text011.geometry} material={materials.Frontgate_text_neon} position={[-0.68, 82.16, 672.82]} rotation={[Math.PI / 2, 0, Math.PI]} />
        <mesh name="Text013" geometry={nodes.Text013.geometry} material={materials.Frontgate_text_neon} position={[-0.68, 82.16, -149.66]} rotation={[Math.PI / 2, 0, Math.PI]} />
        <mesh name="Text014" geometry={nodes.Text014.geometry} material={materials.Frontgate_text_neon} position={[-81.25, 118.24, -922.17]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh name="Text015" geometry={nodes.Text015.geometry} material={materials.Frontgate_text_neon} position={[-81.45, 116.15, -2054.49]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh name="Text016" geometry={nodes.Text016.geometry} material={materials.Frontgate_text_neon} position={[-81.76, 113.92, -2828.46]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh name="Text017" geometry={nodes.Text017.geometry} material={materials.Frontgate_text_neon} position={[628.17, 66.19, -2646.21]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh name="Text018" geometry={nodes.Text018.geometry} material={materials.Frontgate_text_neon} position={[629, 65.45, -1170.23]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh name="Text019" geometry={nodes.Text019.geometry} material={materials.Frontgate_text_neon} position={[515.57, 22.48, 578.98]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh name="Text020" geometry={nodes.Text020.geometry} material={materials.Frontgate_text_neon} position={[640.87, 7.68, 480.43]} rotation={[Math.PI / 2, 0, Math.PI]} />
        <mesh name="Text003" geometry={nodes.Text003.geometry} material={materials.Neon_text2} position={[1040.44, -60.21, 78.98]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh name="Text012" geometry={nodes.Text012.geometry} material={materials.Checkpoint_in_neon} position={[-1251.01, 353.68, 527.21]} rotation={[Math.PI / 2, 0, Math.PI]} />
        <mesh name="Text021" geometry={nodes.Text021.geometry} material={materials.Checkpoint_in_neon} position={[-1251.01, 353.68, 539.21]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Text022" geometry={nodes.Text022.geometry} material={materials.Frontgate_text_neon} position={[628.91, 72.69, -1874.81]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh name="Text023" geometry={nodes.Text023.geometry} material={materials.Frontgate_text_neon} position={[563.29, -28.5, -678.15]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh name="Text002" geometry={nodes.Text002.geometry} material={materials.Frontgate_text_neon} position={[211.87, 135.49, 1116.06]} rotation={[Math.PI / 2, 0, -0.35]} />
        <mesh name="Text004" geometry={nodes.Text004.geometry} material={materials.Frontgate_text_neon} position={[227.87, 100.57, 1102.14]} rotation={[Math.PI / 2, 0, -0.35]} />
        <mesh name="Text" geometry={nodes.Text.geometry} material={materials.Frontgate_text_neon} position={[219.09, 68.81, 1106.69]} rotation={[Math.PI / 2, 0, -0.35]} scale={49.71} />
      </group>
    </group>
  )
}

useGLTF.preload('/Texts2-transformed.glb')
