/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 TirutsavaLogos.glb -T
*/

import { useAnimations, useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'

export function TirutsavaLogos(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/TirutsavaLogos-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group scale={0.1} ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Curve001" geometry={nodes.Curve001.geometry} material={materials['Neon_text5.001']} position={[402.14, -3.05, 1879.89]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Curve002" geometry={nodes.Curve002.geometry} material={materials.Neon_text5} position={[175.38, 196.8, 1111.94]} rotation={[Math.PI / 2, 0, -0.34]} />
        <mesh name="Curve003" geometry={nodes.Curve003.geometry} material={materials.Neon_text3} position={[90.98, 69.85, 707.26]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh name="Curve004" geometry={nodes.Curve004.geometry} material={materials.Neon_text3} position={[90.98, 69.85, -120.38]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh name="Curve005" geometry={nodes.Curve005.geometry} material={materials.Neon_text3} position={[-81.72, 196.03, -1025.95]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh name="Curve006" geometry={nodes.Curve006.geometry} material={materials.Neon_text3} position={[-81.72, 196.03, -2153]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh name="Curve007" geometry={nodes.Curve007.geometry} material={materials.Neon_text3} position={[-81.72, 196.03, -2924.97]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh name="Curve008" geometry={nodes.Curve008.geometry} material={materials.Neon_text3} position={[629.73, 149.59, -2541.71]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh name="Curve009" geometry={nodes.Curve009.geometry} material={materials.Neon_text3} position={[629.73, 149.59, -1766.43]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh name="Curve010" geometry={nodes.Curve010.geometry} material={materials.Neon_text3} position={[629.73, 149.59, -1065]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh name="Curve011" geometry={nodes.Curve011.geometry} material={materials.Neon_text3} position={[563.62, 36.96, -679.45]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh name="Curve012" geometry={nodes.Curve012.geometry} material={materials.Neon_text3} position={[515.63, 2.9, 701.99]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh name="Curve014" geometry={nodes.Curve014.geometry} material={materials.Neon_text2} position={[1042.37, -58.31, -45.25]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.86} />
        <mesh name="Curve013" geometry={nodes.Curve013.geometry} material={materials.Neon} position={[-1342.71, 420.21, 480.73]} rotation={[Math.PI / 2, 0, Math.PI]} />
      </group>
    </group>
  )
}

useGLTF.preload('/TirutsavaLogos-transformed.glb')
