/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Walls.glb -T
*/

import { useAnimations, useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'

export function Walls(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Walls-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group scale={0.1} ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Cube436" geometry={nodes.Cube436.geometry} material={materials['Concrete.002']} position={[-583.31, -48.7, -4396.4]} rotation={[0, 0.1, 0]} />
        <mesh name="Cube601" geometry={nodes.Cube601.geometry} material={materials['Concrete.002']} position={[1471.39, -61.81, -3473.88]} />
        <mesh name="Cube602" geometry={nodes.Cube602.geometry} material={materials['Concrete.002']} position={[320.42, -68.24, 1083.93]} />
        <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials['Concrete.002']} position={[155.52, -68.24, 928.01]} />
        <mesh name="Cube329" geometry={nodes.Cube329.geometry} material={materials['Concrete.002']} position={[-721.65, -99.89, -1080.03]} />
        <mesh name="Cube434" geometry={nodes.Cube434.geometry} material={materials['Concrete.002']} position={[-1576.88, 240.69, -721.92]} />
        <mesh name="Cube331" geometry={nodes.Cube331.geometry} material={materials['Concrete.002']} position={[-249.83, -65.04, -3401.16]} rotation={[0, 1.57, 0]} />
        <mesh name="Cube604" geometry={nodes.Cube604.geometry} material={materials['Concrete.002']} position={[-856.39, -65.15, -3400.52]} />
        <mesh name="Cube330" geometry={nodes.Cube330.geometry} material={materials['Concrete.002']} position={[-249.83, -46.47, -3098.13]} rotation={[0, 1.57, 0]} />
        <mesh name="Cube301" geometry={nodes.Cube301.geometry} material={materials['Concrete.002']} position={[529.05, -60.06, 879.8]} />
        <mesh name="Cube332" geometry={nodes.Cube332.geometry} material={materials['Concrete.002']} position={[1156.8, -61.81, -3042.37]} />
        <mesh name="Cube303" geometry={nodes.Cube303.geometry} material={materials['Concrete.002']} position={[320.42, -68.44, 916.77]} />
        <mesh name="Cube581" geometry={nodes.Cube581.geometry} material={materials.Building_material} position={[1099.27, -39.31, 1845.57]} />
        <mesh name="Cube582" geometry={nodes.Cube582.geometry} material={materials.Building_material} position={[-927.86, -39.31, 1845.57]} />
        <mesh name="Cube585" geometry={nodes.Cube585.geometry} material={materials.Building_material} position={[-2128.38, -39.31, 651.04]} rotation={[0, 1.57, 0]} />
        <mesh name="Cube586" geometry={nodes.Cube586.geometry} material={materials.Building_material} position={[1665.08, -39.31, 647.44]} rotation={[0, 1.57, 0]} />
        <mesh name="Cube587" geometry={nodes.Cube587.geometry} material={materials.Building_material} position={[474.64, -39.31, -5520.24]} />
        <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['Concrete.002']} position={[393.91, -82.44, -3253.83]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Walls-transformed.glb')
