/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 WindowFrames.glb -T
*/

import { useAnimations, useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'

export function WindowFrames(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/WindowFrames-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group scale={0.1} ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Cube448" geometry={nodes.Cube448.geometry} material={materials.Lab1building_material} position={[666.66, 4.53, -1328.86]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube449" geometry={nodes.Cube449.geometry} material={materials.Lab1building_material} position={[1059.25, 17.83, -1329.15]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube450" geometry={nodes.Cube450.geometry} material={materials.Lab1building_material} position={[580.37, -26.18, -1329.25]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube451" geometry={nodes.Cube451.geometry} material={materials.Lab1building_material} position={[666.66, 4.53, -1017.73]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube456" geometry={nodes.Cube456.geometry} material={materials.Lab1building_material} position={[1059.25, 17.83, -1018.02]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube483" geometry={nodes.Cube483.geometry} material={materials.Lab1building_material} position={[666.66, 79.21, -1017.73]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube488" geometry={nodes.Cube488.geometry} material={materials.Lab1building_material} position={[1059.25, 92.51, -1018.02]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube489" geometry={nodes.Cube489.geometry} material={materials.Lab1building_material} position={[666.66, 81.66, -1328.86]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube502" geometry={nodes.Cube502.geometry} material={materials.Lab1building_material} position={[1059.25, 94.95, -1329.15]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube445" geometry={nodes.Cube445.geometry} material={materials.Lab1building_material} position={[666.66, 4.53, -2032.7]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube446" geometry={nodes.Cube446.geometry} material={materials.Lab1building_material} position={[1059.25, 17.83, -2032.99]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube447" geometry={nodes.Cube447.geometry} material={materials.Lab1building_material} position={[580.37, -26.18, -2033.66]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube457" geometry={nodes.Cube457.geometry} material={materials.Lab1building_material} position={[666.66, 4.53, -1721.78]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube458" geometry={nodes.Cube458.geometry} material={materials.Lab1building_material} position={[1059.25, 17.83, -1722.07]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube307" geometry={nodes.Cube307.geometry} material={materials.Lab1building_material} position={[666.66, 71.42, -2032.7]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube372" geometry={nodes.Cube372.geometry} material={materials.Lab1building_material} position={[1059.25, 84.71, -2032.99]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube373" geometry={nodes.Cube373.geometry} material={materials.Lab1building_material} position={[666.66, 80.41, -1721.78]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube387" geometry={nodes.Cube387.geometry} material={materials.Lab1building_material} position={[1059.25, 93.7, -1722.07]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube442" geometry={nodes.Cube442.geometry} material={materials.Lab1building_material} position={[666.66, 4.53, -2808.28]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube443" geometry={nodes.Cube443.geometry} material={materials.Lab1building_material} position={[1059.25, 17.83, -2808.56]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube444" geometry={nodes.Cube444.geometry} material={materials.Lab1building_material} position={[580.37, -26.18, -2809.24]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube459" geometry={nodes.Cube459.geometry} material={materials.Lab1building_material} position={[666.66, 4.53, -2496.86]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube460" geometry={nodes.Cube460.geometry} material={materials.Lab1building_material} position={[1059.25, 17.83, -2497.15]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube151" geometry={nodes.Cube151.geometry} material={materials.Lab1building_material} position={[666.66, 78.63, -2496.86]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube162" geometry={nodes.Cube162.geometry} material={materials.Lab1building_material} position={[1059.25, 91.92, -2497.15]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube163" geometry={nodes.Cube163.geometry} material={materials.Lab1building_material} position={[666.66, 71.16, -2808.28]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube176" geometry={nodes.Cube176.geometry} material={materials.Lab1building_material} position={[1059.25, 84.45, -2808.56]} rotation={[0, -1.57, 0]} />
        <mesh name="Cube439" geometry={nodes.Cube439.geometry} material={materials.Lab1building_material} position={[-113.15, 38.37, -2659.12]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Cube440" geometry={nodes.Cube440.geometry} material={materials.Lab1building_material} position={[-505.73, 51.66, -2660.08]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Cube441" geometry={nodes.Cube441.geometry} material={materials.Lab1building_material} position={[-26.85, 7.66, -2660.04]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Cube463" geometry={nodes.Cube463.geometry} material={materials.Lab1building_material} position={[-113.15, 38.37, -2970.24]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Cube464" geometry={nodes.Cube464.geometry} material={materials.Lab1building_material} position={[-505.73, 51.66, -2970.98]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Cube124" geometry={nodes.Cube124.geometry} material={materials.Lab1building_material} position={[-113.15, 116.54, -2659.12]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Cube134" geometry={nodes.Cube134.geometry} material={materials.Lab1building_material} position={[-505.73, 129.84, -2660.08]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Cube137" geometry={nodes.Cube137.geometry} material={materials.Lab1building_material} position={[-113.15, 109.88, -2970.24]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Cube150" geometry={nodes.Cube150.geometry} material={materials.Lab1building_material} position={[-505.73, 123.17, -2970.98]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Cube407" geometry={nodes.Cube407.geometry} material={materials.Lab1building_material} position={[-113.15, 38.37, -1888.82]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Cube437" geometry={nodes.Cube437.geometry} material={materials.Lab1building_material} position={[-505.73, 51.66, -1889.56]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Cube438" geometry={nodes.Cube438.geometry} material={materials.Lab1building_material} position={[-26.85, 7.66, -1889.56]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Cube461" geometry={nodes.Cube461.geometry} material={materials.Lab1building_material} position={[-113.15, 38.37, -2199.45]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Cube462" geometry={nodes.Cube462.geometry} material={materials.Lab1building_material} position={[-505.73, 51.66, -2200.19]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Cube030" geometry={nodes.Cube030.geometry} material={materials.Lab1building_material} position={[-113.15, 110.06, -2199.45]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Cube110" geometry={nodes.Cube110.geometry} material={materials.Lab1building_material} position={[-505.73, 123.35, -2200.19]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Cube111" geometry={nodes.Cube111.geometry} material={materials.Lab1building_material} position={[-113.15, 112.68, -1888.82]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Cube123" geometry={nodes.Cube123.geometry} material={materials.Lab1building_material} position={[-505.73, 125.97, -1889.56]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Cube391" geometry={nodes.Cube391.geometry} material={materials.Lab1building_material} position={[-113.15, 38.37, -762.34]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Cube392" geometry={nodes.Cube392.geometry} material={materials.Lab1building_material} position={[-505.73, 51.66, -763.07]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Cube465" geometry={nodes.Cube465.geometry} material={materials.Lab1building_material} position={[-113.15, 38.37, -1073.24]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Cube466" geometry={nodes.Cube466.geometry} material={materials.Lab1building_material} position={[-505.73, 51.66, -1073.97]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Cube010" geometry={nodes.Cube010.geometry} material={materials.Lab1building_material} position={[-113.15, 118.1, -762.34]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Cube012" geometry={nodes.Cube012.geometry} material={materials.Lab1building_material} position={[-505.73, 131.39, -763.07]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Cube018" geometry={nodes.Cube018.geometry} material={materials.Lab1building_material} position={[-113.15, 117.22, -1073.24]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Cube020" geometry={nodes.Cube020.geometry} material={materials.Lab1building_material} position={[-505.73, 130.51, -1073.97]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Cube393" geometry={nodes.Cube393.geometry} material={materials.Lab1building_material} position={[-26.85, 7.66, -763.07]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Cube136" geometry={nodes.Cube136.geometry} material={materials.Lab1building_material} position={[-1406.04, 357.05, 716.73]} />
        <mesh name="Cube335" geometry={nodes.Cube335.geometry} material={materials.Lab1building_material} position={[-1405.88, 278.37, 716.73]} />
        <mesh name="Cube336" geometry={nodes.Cube336.geometry} material={materials.Lab1building_material} position={[-1405.65, 196.28, 716.73]} />
        <mesh name="Cube388" geometry={nodes.Cube388.geometry} material={materials.Lab1building_material} position={[-1405.3, 354.72, 646.59]} />
        <mesh name="Cube389" geometry={nodes.Cube389.geometry} material={materials.Lab1building_material} position={[-1405.3, 278.22, 646.59]} />
        <mesh name="Cube390" geometry={nodes.Cube390.geometry} material={materials.Lab1building_material} position={[-1405.3, 188.01, 646.59]} />
      </group>
    </group>
  )
}

useGLTF.preload('/WindowFrames-transformed.glb')
